{
 "title": "00 Overview",
 "tags": [ "PV" ],
 "time": { "from": "now-1d/d", "to": "now/d" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "days",
    "label": "Tage",
    "query": "0d,1d,2d,3d,4d,5d,6d,7d,8d,9d,10d"
   },
   { "name": "DBname", "query": "${VAR_DBNAME}" },
   { "name": "month", "label": "Monat", "query": "0M,1M,2M,3M,4M,5M" },
   { "name": "year", "label": "Jahr", "query": "0y,1y,2y,3y,4y,5y,6y,7y,8y" },
   {
    "name": "current_time",
    "query": "Select concat(TIME_TO_SEC(CURTIME()),'s')"
   },
   { "name": "PVarea", "query": "${VAR_PVAREA}" },
   { "name": "Wirkgrad", "query": "${VAR_WIRKGRAD}" },
   { "name": "fitmethod", "query": "${VAR_FITMETHOD}" },
   { "name": "maxEinspeisen", "query": "${VAR_MAXEINSPEISEN}" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Aktuell\" as \"type\",\n  dcPowerPV AS \"PV\",\n  BatPowerLaden AS \"Bat Laden\",\n  if (BatPowerladen>0 AND EinspeisenPower>5300,BatPowerladen,if(EinspeisenPower+BatPowerladen>5300,EinspeisenPower+BatPowerladen-5300,0)) AS \"Bat Laden (frei)\",\n  BatPowerEntladen AS \"Bat\",\n  acPower AS \"WR\",\n  EinspeisenPower AS \"Einspeisen\",\n  BatStateOfCharge AS \"Bat Status\",\n  AktHomeConsumption AS \"Hausverbrauch\",\n  AktHomeConsumptionSolar AS \"Hausverbrauch PV\",\n  AktHomeConsumptionBat AS \"Hausverbrauch Bat\",\n  AktHomeConsumptionGrid AS \"Hausverbrauch Netz\"\nFROM WR_Daten\nORDER BY ID DESC LIMIT 1"
    }
   ]
  },
  { "title": "Tag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Sum (heute)\" as \"type\",\n  Date_format(TIMESTAMP,'%Y-%m-%d') as \"Datum\",\n  sum(PV_kWh) AS \"PV\",\n  sum(BatLaden_kWh) AS \"Bat Laden\",\n  sum(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  sum(BatEntladen_kWh) AS \"Bat\",\n  sum(ac_kWh) AS \"WR\",\n  sum(Einspeisen_kWh) AS \"Einspeisen\",\n  sum(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  sum(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  sum(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  sum(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  to_days(TIMESTAMP)=to_days(FROM_UNIXTIME($__unixEpochTo()))\nunion all\nSELECT\n  \"Sum (gestern)\" as \"type\",\n  Date_format(TIMESTAMP,'%Y-%m-%d') as \"Datum\",\n  sum(PV_kWh) AS \"PV\",\n  sum(BatLaden_kWh) AS \"Bat Laden\",\n  sum(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  sum(BatEntladen_kWh) AS \"Bat\",\n  sum(ac_kWh) AS \"WR\",\n  sum(Einspeisen_kWh) AS \"Einspeisen\",\n  sum(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  sum(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  sum(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  sum(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  to_days(TIMESTAMP)=to_days(FROM_UNIXTIME($__unixEpochFrom()))"
    }
   ]
  },
  {
   "title": "PV Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  avg(dcPowerPV) AS \"PV Power\",\n  avg(BatPowerEntLaden) AS \"Bat Power\",\n  avg(acPower) AS WR,\n  -avg(BatPowerLaden) AS \"Bat Laden\",\n  avg(EinspeisenPower) AS Einspeisen,\n  sum(AktHomeConsumptionSolar+AktHomeConsumptionBat)/sum(acPower) AS Eigenverbrauchsanteil\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY time_sec DIV 300"
    },
    {
     "rawSql": "SELECT\n  time_sec-1800 AS \"time\",\n  DCsim as value,\n  \"Prognose\" as metric\nFROM DWD_SIM_Daten\nWHERE\n  $__unixEpochFilter(time_sec-1800)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "PV Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochFrom()+hour(TIMESTAMP)*3600+minute(TIMESTAMP)*60 as time_sec,\n  convert(date(TIMESTAMP),char) AS metric,\n  avg(dcPowerPV) AS value\nFROM WR_Daten\nWHERE\n  TIMESTAMP Between TIMESTAMP(Date_format($__timeFrom(),\"%Y-%m-%d 00:00:00\")) AND TIMESTAMP(Date_format($__timeTo(),\"%Y-%m-%d 23:59:59\"))\nGROUP BY time_sec DIV 120"
    }
   ]
  },
  {
   "title": "ac Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochFrom()+hour(TIMESTAMP)*3600+minute(TIMESTAMP)*60 as time_sec,\n  convert(date(TIMESTAMP),char) AS metric,\n  avg(acPower) AS value\nFROM WR_Daten\nWHERE\n  TIMESTAMP Between TIMESTAMP(Date_format($__timeFrom(),\"%Y-%m-%d 00:00:00\")) AND TIMESTAMP(Date_format($__timeTo(),\"%Y-%m-%d 23:59:59\"))\nGROUP BY time_sec DIV 120"
    }
   ]
  },
  {
   "title": "Einspeisen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochFrom()+hour(TIMESTAMP)*3600+minute(TIMESTAMP)*60 as time_sec,\n  convert(date(TIMESTAMP),char) AS metric,\n  avg(EinspeisenPower) AS value\nFROM WR_Daten\nWHERE\n  TIMESTAMP Between TIMESTAMP(Date_format($__timeFrom(),\"%Y-%m-%d 00:00:00\")) AND TIMESTAMP(Date_format($__timeTo(),\"%Y-%m-%d 23:59:59\"))\nGROUP BY time_sec DIV 120"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  operatingStatus\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\nDate_format(TIMESTAMP,'%Y-%m-%d %H:%i') as \"Time\",\noperatingStatus as StatusCode,\n( Case operatingStatus\n  When 0 then 'off'\n  When 1 then 'anfahren'\n  When 2 then 'Leerlauf'  \n  When 3 then 'Einspeisen (MPP)'\n  When 4 then 'abgeregelt'\n  When 5 then 'Einspeisen'\n  Else 'undefined'\n  End) as Status\nFROM (\n    SELECT\n        operatingStatus,time_sec,TIMESTAMP,\n        @rn := CASE WHEN (@prev <> operatingStatus) THEN @rn+1 ELSE @rn END AS rn,\n    \t@prev := operatingStatus\n    FROM (\n        SELECT operatingStatus,time_sec,TIMESTAMP\n        FROM WR_Daten\n        WHERE $__unixEpochFilter(time_sec)\n        ORDER BY ID ) AS a , \n        (SELECT @prev := -1, @rn := 0) AS vars \n) T1 Group BY rn ORDER BY `T1`.`time_sec` ASC"
    }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  \"PV\" AS metric,\n  avg(AktHomeConsumptionSolar) AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY time_sec DIV 300"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"Batterie\" AS metric,\n  avg(AktHomeConsumptionBat) AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY time_sec DIV 300"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"Netz\" AS metric,\n  avg(AktHomeConsumptionGrid) AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY time_sec DIV 300"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"Gsamt\" AS metric,\n  avg(AktHomeConsumption) AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY time_sec DIV 300"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"Autarkie\" AS metric,\n  (avg(AktHomeConsumptionSolar)+avg(AktHomeConsumptionBat))/avg(AktHomeConsumption) AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec) AND AktHomeConsumption>0\nGROUP BY time_sec DIV 300"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  avg(BatPowerEntladen) AS Entladen,\n  avg(BatPowerLaden) AS Laden,\n  avg(BatStateOfCharge) AS Ladestand,\n  avg(BatLaden_Frei) as \"Laden frei\"\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY time_sec DIV 300"
    }
   ]
  },
  { "title": "Tage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Sum (dieser Monat)\" as \"type\",\n  Date_format(TIMESTAMP,'%Y-%m') as \"Datum\",\n  sum(PV_kWh) AS \"PV\",\n  sum(BatLaden_kWh) AS \"Bat Laden\",\n  sum(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  sum(BatEntladen_kWh) AS \"Bat\",\n  sum(ac_kWh) AS \"WR\",\n  sum(Einspeisen_kWh) AS \"Einspeisen\",\n  sum(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  sum(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  sum(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  sum(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  year(TIMESTAMP)=year(FROM_UNIXTIME($__unixEpochTo())) AND month(TIMESTAMP)=month(FROM_UNIXTIME($__unixEpochTo()))\nunion all\nSELECT\n  \"Sum (letzter Monat)\" as \"type\",\n  Date_format(TIMESTAMP,'%Y-%m') as \"Datum\",\n  sum(PV_kWh) AS \"PV\",\n  sum(BatLaden_kWh) AS \"Bat Laden\",\n  sum(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  sum(BatEntladen_kWh) AS \"Bat\",\n  sum(ac_kWh) AS \"WR\",\n  sum(Einspeisen_kWh) AS \"Einspeisen\",\n  sum(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  sum(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  sum(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  sum(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  year(TIMESTAMP)=year(Date_ADD(FROM_UNIXTIME($__unixEpochTo()), interval -1 month)) AND month(TIMESTAMP)=month(Date_ADD(FROM_UNIXTIME($__unixEpochTo()), interval -1 month))"
    }
   ]
  },
  {
   "title": "Ertrag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(HomeConsumptionSolar_kWh) AS PV,\n  sum(HomeConsumptionBat_kWh) AS Batterie,\n  sum(Einspeisen_kWh) AS Einspeisen,\n  sum(ac_kWh) AS \"WR output\",\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(ac_kWh) AS Eigenverbrauchsanteil,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh) AS Eigenverbrauch\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY to_days(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(HomeConsumptionSolar_kWh) AS PV,\n  sum(HomeConsumptionBat_kWh) AS Batterie,\n  sum(HomeConsumptionGrid_kWh) AS Netz,\n  sum(HomeConsumption_kWh) AS Gesamt,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(HomeConsumption_kWh) AS Autarkie\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY to_days(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  \"Ladestand\" AS metric,\n  avg(BatStateOfCharge) AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY time_sec DIV 300"
    }
   ]
  },
  { "title": "Monate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Sum (dieses Jahr)\" as \"type\",\n  year(TIMESTAMP) as \"Datum\",\n  sum(PV_kWh) AS \"PV\",\n  sum(BatLaden_kWh) AS \"Bat Laden\",\n  sum(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  sum(BatEntladen_kWh) AS \"Bat\",\n  sum(ac_kWh) AS \"WR\",\n  sum(Einspeisen_kWh) AS \"Einspeisen\",\n  sum(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  sum(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  sum(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  sum(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  year(TIMESTAMP)=year(FROM_UNIXTIME($__unixEpochTo()))\nunion all\nSELECT\n  \"Sum (letztes Jahr)\" as \"type\",\n  year(TIMESTAMP) as \"Datum\",\n  sum(PV_kWh) AS \"PV\",\n  sum(BatLaden_kWh) AS \"Bat Laden\",\n  sum(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  sum(BatEntladen_kWh) AS \"Bat\",\n  sum(ac_kWh) AS \"WR\",\n  sum(Einspeisen_kWh) AS \"Einspeisen\",\n  sum(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  sum(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  sum(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  sum(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  year(TIMESTAMP)=year(Date_ADD(FROM_UNIXTIME($__unixEpochTo()), interval -1 year))"
    }
   ]
  },
  {
   "title": "Ertrag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(HomeConsumptionSolar_kWh) AS PV,\n  sum(HomeConsumptionBat_kWh) AS Batterie,\n  sum(Einspeisen_kWh) AS Einspeisen,\n  sum(ac_kWh) AS \"WR output\",\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(ac_kWh) AS Eigenverbrauchsanteil,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh) AS Eigenverbrauch\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY year(TIMESTAMP),month(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(HomeConsumptionSolar_kWh) AS PV,\n  sum(HomeConsumptionBat_kWh) AS Batterie,\n  sum(HomeConsumptionGrid_kWh) AS Netz,\n  sum(HomeConsumption_kWh) AS Gesamt,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(HomeConsumption_kWh) AS Autarkie\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY year(TIMESTAMP), month(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  max(ChargeCycles)-min(ChargeCycles) as value,\n  \"Lade Zyklen\" as metrics\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY year(TIMESTAMP), month(TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  sum(BatLaden_kWh) as value,\n  \"Bat Laden\" as metrics\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY year(TIMESTAMP), month(TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  sum(BatEntladen_kWh) as value,\n  \"Bat Entnahme\" as metrics\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY year(TIMESTAMP), month(TIMESTAMP)"
    }
   ]
  },
  { "title": "Jahre", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Sum (overall)\" as \"type\",\n  Date_format(TIMESTAMP,'%Y-%m') as \"Datum\",\n  sum(PV_kWh) AS \"PV\",\n  sum(BatLaden_kWh) AS \"Bat Laden\",\n  sum(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  sum(BatEntladen_kWh) AS \"Bat\",\n  sum(ac_kWh) AS \"WR\",\n  sum(Einspeisen_kWh) AS \"Einspeisen\",\n  sum(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  sum(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  sum(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  sum(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily"
    }
   ]
  },
  {
   "title": "Ertrag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(HomeConsumptionSolar_kWh) AS PV,\n  sum(HomeConsumptionBat_kWh) AS Batterie,\n  sum(Einspeisen_kWh) AS Einspeisen,\n  sum(ac_kWh) AS \"WR output\",\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(ac_kWh) AS Eigenverbrauchsanteil,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh) AS Eigenverbrauch\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY year(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(HomeConsumptionSolar_kWh) AS PV,\n  sum(HomeConsumptionBat_kWh) AS Batterie,\n  sum(HomeConsumptionGrid_kWh) AS Netz,\n  sum(HomeConsumption_kWh) AS Gesamt,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(HomeConsumption_kWh) AS Autarkie\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY year(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  max(ChargeCycles)-min(ChargeCycles) as \"Lade Zyklen\",\n  sum(BatLaden_kWh) as \"Bat Laden\",\n  sum(BatEntladen_kWh) as \"Bat Entnahme\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY year(TIMESTAMP)"
    }
   ]
  }
 ]
}