{
 "title": "01 Heute",
 "tags": [ "PV" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "days",
    "label": "Tage",
    "query": "0d,1d,2d,3d,4d,5d,6d,7d,8d,9d,10d"
   },
   { "name": "DBname", "query": "${VAR_DBNAME}" },
   { "name": "Steuersatz", "query": "0.25,0.3,0.35,0.4" },
   { "name": "maxEinspeisen", "query": "${VAR_MAXEINSPEISEN}" },
   { "name": "PVarea", "query": "${VAR_PVAREA}" },
   { "name": "Wirkgrad", "query": "${VAR_WIRKGRAD}" },
   { "name": "fitmethod", "query": "${VAR_FITMETHOD}" },
   { "name": "grouping", "label": "Gruppierung", "query": "1,5,10,15,30,60" }
  ]
 },
 "panels": [
  { "title": "Aktuelle Werte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Zeit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n  Date_format(TIMESTAMP,'%d.%m.%Y %k:%i') as value\nFROM WR_Daten\nORDER BY time_sec DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum(T1.value_ue) as \"Überschuss\",\n  sum(T1.value_ge) as \"Gewinn\",\n  sum(T1.value_ge-value_ge_no_bat) as \"BatVorteil\"\nFrom\n(SELECT\n    (sum(Gewinne_Verlust.Verkauf-Gewinne_Verlust.BezugKosten-Gewinne_Verlust.MWST-Gewinne_Verlust.Abschreibung)+  IF(sum(Gewinne_Verlust.SteuerlGewinn)>sum(Gewinne_Verlust.Abschreibung+Gewinne_Verlust.MWST),sum(Gewinne_Verlust.Abschreibung+Gewinne_Verlust.MWST-Gewinne_Verlust.SteuerlGewinn)*$Steuersatz,0)) as value_ue,\n  (sum(Gewinne_Verlust.Verkauf+Gewinne_Verlust.Ersparnis-Gewinne_Verlust.MWST-Gewinne_Verlust.Abschreibung)+  IF(sum(Gewinne_Verlust.SteuerlGewinn)>sum(Gewinne_Verlust.Abschreibung+Gewinne_Verlust.MWST),sum(Gewinne_Verlust.Abschreibung+Gewinne_Verlust.MWST-Gewinne_Verlust.SteuerlGewinn)*$Steuersatz,0)) as value_ge,\n  (sum(Gewinne_Verlust_PVonly.Verkauf+Gewinne_Verlust_PVonly.Ersparnis-Gewinne_Verlust_PVonly.MWST-Gewinne_Verlust_PVonly.Abschreibung)+  IF(sum(Gewinne_Verlust_PVonly.SteuerlGewinn)>sum(Gewinne_Verlust_PVonly.Abschreibung+Gewinne_Verlust_PVonly.MWST),sum(Gewinne_Verlust_PVonly.Abschreibung+Gewinne_Verlust_PVonly.MWST-Gewinne_Verlust_PVonly.SteuerlGewinn)*$Steuersatz,0)) as value_ge_no_bat\nFROM Gewinne_Verlust\nJoin Gewinne_Verlust_PVonly on Gewinne_Verlust.time_sec=Gewinne_Verlust_PVonly.time_sec\nGROUP BY year(Gewinne_Verlust.TIMESTAMP) ) T1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  1-sum(ac_kWh)/sum(PV_kWh+BatEntladen_kWh) as \"WR Verlust\",\n  1-sum(BatEntladen_kWh)/sum(BatLaden_kWh) as \"Bat Verlust DC\",\n  sum(BatLaden_kWh-BatEntladen_kWh)/sum(PV_kWh) as \"Bat Verlustanteil\"\nFROM aggregate_WR_Daten_daily\n"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Aktuell\" as \"type\",\n  dcPowerPV AS \"PV\",\n  BatPowerLaden AS \"Bat Laden\",\n  if (BatPowerladen>0 AND EinspeisenPower>floor($maxEinspeisen*0.99),BatPowerladen,if(EinspeisenPower+BatPowerladen>floor($maxEinspeisen*0.99),EinspeisenPower+BatPowerladen-floor($maxEinspeisen*0.99),0)) AS \"Bat Laden (frei)\",\n  BatPowerEntladen AS \"Bat\",\n  acPower AS \"WR\",\n  EinspeisenPower AS \"Einspeisen\",\n  BatStateOfCharge AS \"Bat Status\",\n  AktHomeConsumption AS \"Hausverbrauch\",\n  AktHomeConsumptionSolar AS \"Hausverbrauch PV\",\n  AktHomeConsumptionBat AS \"Hausverbrauch Bat\",\n  AktHomeConsumptionGrid AS \"Hausverbrauch Netz\"\nFROM WR_Daten\nORDER BY ID DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "PV",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec AS time_sec,\n  dcPowerPV as value\nFROM WR_Daten\nORDER BY time_sec DESC Limit 1 "
    }
   ]
  },
  {
   "title": "Batterie Output",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  BatPowerEntLaden-BatPowerLaden AS value\nFROM WR_Daten\nORDER BY time_sec DESC Limit 1"
    }
   ]
  },
  {
   "title": "Einspeisen",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  EinspeisenPower AS value\nFROM WR_Daten\nORDER BY time_sec DESC Limit 1"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  operatingStatus as value\nFROM WR_Daten\nORDER BY time_sec DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  AktHomeConsumption AS value\nFROM WR_Daten\nwhere month(timestamp) = month($__timeTo())\nORDER BY time_sec ASC"
    }
   ]
  },
  {
   "title": "Eigenv. PV",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  AktHomeConsumptionSolar AS value\nFROM WR_Daten\nORDER BY time_sec Desc Limit 1"
    }
   ]
  },
  {
   "title": "Eigenv. Bat",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  AktHomeConsumptionBat AS value\nFROM WR_Daten\nORDER BY time_sec DESC Limit 1"
    }
   ]
  },
  {
   "title": "Netzbezug",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  AktHomeConsumptionGrid AS value\nFROM WR_Daten\nwhere month(timestamp) = month($__timeTo())\nORDER BY time_sec ASC"
    }
   ]
  },
  { "title": "Ausgewählte Zeit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Datum",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Date_format(TIMESTAMP,'%d.%m.%Y') as value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"AVG (per hour)\" as \"type\",\n  avg(dcPowerPV)/1000 AS \"PV\",\n  avg(BatPowerLaden)/1000 AS \"Bat Laden\",\n  avg(BatLaden_Frei)/1000 AS \"Bat Laden (frei)\",\n  avg(BatPowerEntladen)/1000 AS \"Bat\",\n  avg(acPower)/1000 AS \"WR\",\n  avg(EinspeisenPower)/1000 AS \"Einspeisen\",\n  avg(AktHomeConsumption)/1000 AS \"Hausverbrauch\",\n  avg(AktHomeConsumptionSolar)/1000 AS \"Hausverbrauch PV\",\n  avg(AktHomeConsumptionBat)/1000 AS \"Hausverbrauch Bat\",\n  avg(AktHomeConsumptionGrid)/60000 AS \"Hausverbrauch Netz\"\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nunion all\nSELECT\n  \"Sum (timerange)\" as \"type\",\n  sum(dcPowerPV)/60000 AS \"PV\",\n  sum(BatPowerLaden)/60000 AS \"Bat Laden\",\n  sum(BatLaden_Frei)/60000 AS \"Bat Laden (frei)\",\n  sum(BatPowerEntladen)/60000 AS \"Bat\",\n  sum(acPower)/60000 AS \"WR\",\n  sum(EinspeisenPower)/60000 AS \"Einspeisen\",\n  sum(AktHomeConsumption)/60000 AS \"Hausverbrauch\",\n  sum(AktHomeConsumptionSolar)/60000 AS \"Hausverbrauch PV\",\n  sum(AktHomeConsumptionBat)/60000 AS \"Hausverbrauch Bat\",\n  sum(AktHomeConsumptionGrid)/60000 AS \"Hausverbrauch Netz\"\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nunion all\nSELECT\n  \"Sum (overall)\" as \"type\",\n  sum(PV_kWh) AS \"PV\",\n  sum(BatLaden_kWh) AS \"Bat Laden\",\n  sum(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  sum(BatEntladen_kWh) AS \"Bat\",\n  sum(ac_kWh) AS \"WR\",\n  sum(Einspeisen_kWh) AS \"Einspeisen\",\n  sum(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  sum(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  sum(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  sum(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily"
    }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  avg(AktHomeConsumptionSolar) AS \"PV\",\n  avg(AktHomeConsumptionBat) AS \"Batterie\",\n  avg(AktHomeConsumptionGrid) AS \"Netz\",\n  avg(AktHomeConsumption) AS \"Gesamt\",\n  1-LEAST((sum(AktHomeConsumptionGrid))/sum(AktHomeConsumption),1) AS \"Autarkie\"\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY time_sec DIV ($grouping*60)"
    }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 18 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(AktHomeConsumptionSolar/60) over (order by id) AS \"PV\",\n  sum(AktHomeConsumptionBat/60) over (order by id) AS \"Batterie\",\n  sum(AktHomeConsumptionGrid/60) over (order by id) AS \"Netz\",\n  sum(AktHomeConsumption/60) over (order by id) AS \"Gsamt\"\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)"
    }
   ]
  },
  {
   "title": "PV Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  avg(dcPowerPV) AS \"PV Power\",\n  avg(BatPowerEntLaden) AS \"Bat Power\",\n  -avg(BatPowerLaden) AS \"Bat Laden\",\n  avg(acPower) AS \"WR\",\n  avg(EinspeisenPower) AS \"Einspeisen\",\n  LEAST(sum(AktHomeConsumptionSolar+AktHomeConsumptionBat)/sum(acPower),1) AS \"Eigenverbrauchsanteil\"\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY time_sec DIV ($grouping*60)"
    },
    {
     "rawSql": "SELECT\n  time_sec-1800 AS \"time\",\n  DCsim as value,\n  \"Prognose\" as metric\nFROM DWD_SIM_Daten\nWHERE\n  $__unixEpochFilter(time_sec-1800)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "PV Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 26 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(dcPowerPV/60) over (order by id) AS \"PV Power\",\n  sum(BatPowerEntLaden/60) over (order by id) AS \"Bat Power\",\n  sum(acPower/60) over (order by id) AS \"WR\",\n  sum(BatPowerLaden/60) over (order by id) AS \"Bat Laden\",\n  sum(EinspeisenPower/60) over (order by id) AS \"Einspeisen\"\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)"
    },
    {
     "rawSql": "SELECT\n  time_sec-1800 AS \"time\",\n  sum(DCsim) over (order by time_sec) as Prognose\nFROM DWD_SIM_Daten\nWHERE\n  $__unixEpochFilter(time_sec-1800)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  operatingStatus\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\nDate_format(TIMESTAMP,'%d.%m.%Y %k:%i') as \"Zeit\",\noperatingStatus as StatusCode,\n( Case operatingStatus\n  When 0 then 'off'\n  When 1 then 'anfahren'\n  When 2 then 'Leerlauf'  \n  When 3 then 'Einspeisen (MPP)'\n  When 4 then 'abgeregelt'\n  When 5 then 'Einspeisen'\n  Else 'undefined'\n  End) as Status\nFROM (\n    SELECT\n        operatingStatus,time_sec,TIMESTAMP,\n        @rn := CASE WHEN (@prev <> operatingStatus) THEN @rn+1 ELSE @rn END AS rn,\n    \t@prev := operatingStatus\n    FROM (\n        SELECT operatingStatus,time_sec,TIMESTAMP\n        FROM WR_Daten\n        WHERE $__unixEpochFilter(time_sec)\n        ORDER BY ID ) AS a , \n        (SELECT @prev := -1, @rn := 0) AS vars \n) T1 Group BY rn ORDER BY `T1`.`time_sec` DESC"
    }
   ]
  },
  {
   "title": "Spannungen / Ströme",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  avg(dc1Voltage) as \"String 1 Spannung\",\n  avg(dc2Voltage) as \"String 2 Spannung\",\n  avg(dc1Current) as \"String 1 Strom\",\n  avg(dc2Current) as \"String 2 Strom\"\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY time_sec DIV ($grouping*60)"
    },
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  avg(BatVoltage) as \"Bat Spannung\",\n  avg(if(BatCurrentDir = 0,BatCurrent,0)) as \"Bat Strom Laden\",\n  avg(if(BatCurrentDir = 1,BatCurrent,0)) as \"Bat Strom Entnahme\"\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY time_sec DIV ($grouping*60)"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  avg(BatPowerEntladen) AS \"Entladen\",\n  avg(BatPowerLaden) AS \"Laden\",\n  avg(BatStateOfCharge) as \"Ladestand\",\n  avg(BatLaden_Frei) AS \"Laden frei\"\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY time_sec DIV ($grouping*60)"
    }
   ]
  }
 ]
}