{
 "title": "02 Woche",
 "description": "aktuelles Jahr",
 "tags": [ "PV" ],
 "time": { "from": "now-6d/d", "to": "now/d" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "timeshift", "label": "Tag", "query": "0d,1d,2d,3d,4d,5d,6d,1w,2w,3w" },
   {
    "name": "current_time",
    "query": "Select concat(86400+3-TIME_TO_SEC(CURRENT_TIME()),'s')"
   },
   { "name": "grouping", "query": "${VAR_GROUPING}" }
  ]
 },
 "panels": [
  {
   "title": "Datum",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  concat(Date_format(min(TIMESTAMP),'%d.%m'),' bis ',Date_format(max(TIMESTAMP),'%d.%m.%Y')) as value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec DESC"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT  \nDate_format(TIMESTAMP,'%d.%m.%Y %k:%i') as Zeit,\noperatingStatus as StatusCode,\n( Case operatingStatus\n  When 0 then 'off'\n  When 1 then 'anfahren'\n  When 2 then 'Leerlauf'  \n  When 3 then 'Einspeisen (MPP)'\n  When 4 then 'abgeregelt'\n  When 5 then 'Einspeisen'\n  Else 'undefined'\n  End) as Status\nFROM (\n    SELECT\n        operatingStatus,time_sec,TIMESTAMP,\n        @rn := CASE WHEN (@prev <> operatingStatus) THEN @rn+1 ELSE @rn END AS rn,\n    \t@prev := operatingStatus\n    FROM (\n        SELECT operatingStatus,time_sec,TIMESTAMP\n        FROM WR_Daten\n        WHERE $__unixEpochFilter(time_sec)\n        ORDER BY ID ) AS a , \n        (SELECT @prev := -1, @rn := 0) AS vars \n) T1 Group BY rn ORDER BY `T1`.`time_sec` DESC"
    }
   ]
  },
  {
   "title": "Hausverbrauch (Tagesmittel, ausgewählte Woche)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochFrom()+hour(min(TIMESTAMP))*3600 as time_sec,\n  avg(HomeConsumptionSolar_kWh) AS PV,\n  avg(HomeConsumptionBat_kWh) AS Batterie,\n  avg(HomeConsumptionGrid_kWh) AS Netz,\n  avg(HomeConsumption_kWh) AS Gesamt,\n  1-LEAST(sum(HomeConsumptionGrid_kWh)/sum(HomeConsumption_kWh),1) AS Autarkie\nFROM aggregate_WR_Daten_hourly\nWHERE\n    DATE(TIMESTAMP) Between DATE_SUB(DATE(Date_format($__timeFrom(),\"%Y-%m-%d\")), INTERVAL 6 DAY) AND DATE(Date_format($__timeFrom(),\"%Y-%m-%d\"))\nGROUP BY HOUR(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "PV Power (max Werte)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec+3600 as time_sec,\n  \"WR\" AS metric,\n  max(acPower) AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  max(dcPowerPV) AS \"PV Power\"\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec+2*3600 as time_sec,\n  \"Bat Power\"  AS metric,\n  max(BatPowerEntLaden) AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n    time_sec+3*3600 as time_sec,\n  \"Bat Laden\"  AS metric,\n  max(BatPowerLaden) AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n    time_sec+4*3600 as time_sec,\n  \"Einspeisen\"  AS metric,\n  max(EinspeisenPower) AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "PV Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochFrom()+hour(TIMESTAMP)*3600+minute(TIMESTAMP)*60 as time_sec,\n  Date_format(TIMESTAMP,'%d.%m.%Y') AS metric,\n  avg(dcPowerPV) AS value\nFROM WR_Daten\nWHERE\n  DATE(TIMESTAMP) Between DATE_SUB(DATE(Date_format($__timeFrom(),\"%Y-%m-%d\")), INTERVAL 6 DAY) AND DATE(Date_format($__timeFrom(),\"%Y-%m-%d\"))\nGROUP BY time_sec DIV 1200"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"AVG (per day)\" as \"type\",\n  concat(Date_format(TIMESTAMP,'%d.%m.'),' bis ',Date_format(max(TIMESTAMP),'%d.%m.%Y')) as Datum,\n  avg(PV_kWh) AS \"PV\",\n  avg(BatLaden_kWh) AS \"Bat Laden\",\n  avg(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  avg(BatEntladen_kWh) AS \"Bat\",\n  avg(ac_kWh) AS \"WR\",\n  avg(Einspeisen_kWh) AS \"Einspeisen\",\n  avg(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  avg(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  avg(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  avg(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nunion all\nSELECT\n  \"Sum (timerange)\" as \"type\",\n  concat(Date_format(TIMESTAMP,'%d.%m.'),' bis ',Date_format(max(TIMESTAMP),'%d.%m.%Y')) as Datum,\n  sum(PV_kWh) AS \"PV\",\n  sum(BatLaden_kWh) AS \"Bat Laden\",\n  sum(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  sum(BatEntladen_kWh) AS \"Bat\",\n  sum(ac_kWh) AS \"WR\",\n  sum(Einspeisen_kWh) AS \"Einspeisen\",\n  sum(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  sum(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  sum(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  sum(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nunion all\nSELECT\n  \"Sum (overall)\" as \"type\",\n  Date_format(TIMESTAMP,'%d.%m.%Y') as Datum,\n  sum(PV_kWh) AS \"PV\",\n  sum(BatLaden_kWh) AS \"Bat Laden\",\n  sum(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  sum(BatEntladen_kWh) AS \"Bat\",\n  sum(ac_kWh) AS \"WR\",\n  sum(Einspeisen_kWh) AS \"Einspeisen\",\n  sum(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  sum(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  sum(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  sum(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily\n"
    }
   ]
  },
  {
   "title": "Ertrag",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec AS time_sec,\n  sum(HomeConsumptionSolar_kWh) AS PV,\n  sum(HomeConsumptionBat_kWh) AS Batterie,\n  sum(Einspeisen_kWh) AS Einspeisen,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(ac_kWh) AS Eigenverbrauchsanteil,\n  sum(ac_kWh) AS \"WR output\",\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh) AS Eigenverbrauch\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(HomeConsumptionSolar_kWh) AS PV,\n  sum(HomeConsumptionBat_kWh) AS Batterie,\n  sum(HomeConsumptionGrid_kWh) AS Netz,\n  sum(HomeConsumption_kWh) AS Gesamt,\n  1-LEAST(sum(HomeConsumptionGrid_kWh)/sum(HomeConsumption_kWh),1) AS Autarkie\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Wirkungsgrade",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  \"WR\" AS metric,\n  sum(ac_kWh)/sum(PV_kWh-BatLaden_kWh+BatEntladen_kWh) AS value\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  avg(BatTemperature) as value,\n  \"Bat.Temperatur\" as metric\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"Bat (Eigenverbrauch)\" AS metric,\n  sum(AktHomeConsumptionBat)/sum(acPower) AS value\nFROM WR_Daten\nWHERE\n  AktHomeConsumptionBat>1 and dcPowerPV<1 and $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"Anteil int. Laden\" AS metric,\n  sum(BatLaden_frei_kWh)/sum(BatLaden_kWh) AS value\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Autarkie",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec as time_sec,\n  \"mit Bat\" AS metric,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(HomeConsumption_kWh) AS value\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec as time_sec,\n  \"ohne Bat\" AS metric,\n  sum(HomeConsumptionSolar_kWh)/sum(HomeConsumption_kWh) AS value\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Eigenverbrauch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  \"mit Bat\" AS metric,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(ac_kWh) AS value\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"ohne Bat\" AS metric,\n  sum(HomeConsumptionSolar_kWh)/sum(ac_kWh) AS value\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "PV Power",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  dcPowerPV as value,\n  \"PV Power\" as metric\nFROM WR_Daten\nWHERE $__unixEpochFilter(time_sec)\nORDER BY ID ASC"
    }
   ]
  },
  {
   "title": "Autarkie",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  \"Autarkie\" AS metric,\n  Autarkie AS value\nFROM aggregate_WR_Daten_hourly\nWHERE\n  $__unixEpochFilter(time_sec)"
    }
   ]
  },
  {
   "title": "Batterie Ent-/Laden",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 13, "w": 12, "x": 6, "y": 76 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  -(BatEntladen_kWh) as value,\n  \"Bat Entladen\" as metric\nFROM aggregate_WR_Daten_hourly\nWHERE $__unixEpochFilter(time_sec)"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  BatLaden_kWh as value,\n  \"Bat Laden\" as metric\nFROM aggregate_WR_Daten_hourly\nWHERE $__unixEpochFilter(time_sec)"
    }
   ]
  }
 ]
}