{
 "title": "03 Monat",
 "description": "aktueller Monat",
 "tags": [ "PV" ],
 "time": { "from": "now/M", "to": "now/M" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "timeshift", "label": "Monat", "query": "0M,1M,2M,3M,4M,5M" },
   {
    "name": "current_time",
    "query": "Select concat(86400+3-TIME_TO_SEC(CURRENT_TIME()),'s')"
   },
   { "name": "grouping", "query": "${VAR_GROUPING}" },
   { "name": "PVarea", "query": "${VAR_PVAREA}" },
   { "name": "Wirkgrad", "query": "${VAR_WIRKGRAD}" },
   { "name": "fitmethod", "query": "${VAR_FITMETHOD}" }
  ]
 },
 "panels": [
  {
   "title": "String Spannungen (min-max)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date(timestamp) AS \"time\",\n  \"String 1 Spannung\" AS metric,\n  avg(dc1Voltage) as value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec) and dc1Voltage > 300\nGROUP by to_days(timestamp)"
    },
    {
     "rawSql": "SELECT\n  date(timestamp) AS \"time\",\n  \"String 1 Spannung (max)\" AS metric,\n  max(dc1Voltage) as value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec) and dc1Voltage > 300\nGROUP by to_days(timestamp)"
    },
    {
     "rawSql": "SELECT\n  date(timestamp) AS \"time\",\n  \"String 1 Spannung (min)\" AS metric,\n  min(dc1Voltage) as value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec) and hour(timestamp) between 11 and 15\nGROUP by to_days(timestamp)"
    },
    {
     "rawSql": "SELECT\n  date(timestamp) AS \"time\",\n  \"String 2 Spannung\" AS metric,\n  avg(dc2Voltage) as value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec) and dc2Voltage > 300\nGROUP by to_days(timestamp)"
    },
    {
     "rawSql": "SELECT\n  date(timestamp) AS \"time\",\n  \"String 2 Spannung (max)\" AS metric,\n  max(dc2Voltage) as value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec) and dc2Voltage > 300\nGROUP by to_days(timestamp)"
    },
    {
     "rawSql": "SELECT\n  date(timestamp) AS \"time\",\n  \"String 2 Spannung (min)\" AS metric,\n  min(dc2Voltage) as value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec) and hour(timestamp) between 11 and 15\nGROUP by to_days(timestamp)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT  \nTIMESTAMP as \"Time\",\noperatingStatus as StatusCode\nFROM (\n    SELECT\n        operatingStatus,time_sec,TIMESTAMP,\n        @rn := CASE WHEN (@prev <> operatingStatus) THEN @rn+1 ELSE @rn END AS rn,\n    \t@prev := operatingStatus\n    FROM (\n        SELECT operatingStatus,time_sec,TIMESTAMP\n        FROM WR_Daten\n        WHERE $__unixEpochFilter(time_sec)\n        ORDER BY ID ) AS a , \n        (SELECT @prev := -1, @rn := 0) AS vars \n) T1 Group BY rn ORDER BY `T1`.`time_sec` ASC"
    }
   ]
  },
  {
   "title": "Datum",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  Date_format(TIMESTAMP,'%M %Y') as value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\nDate_format(TIMESTAMP,'%Y-%m-%d %H:%i') as \"Zeit\",\noperatingStatus as StatusCode,\n( Case operatingStatus\n  When 0 then 'off'\n  When 1 then 'anfahren'\n  When 2 then 'Leerlauf'  \n  When 3 then 'Einspeisen (MPP)'\n  When 4 then 'abgeregelt'\n  When 5 then 'Einspeisen'\n  Else 'undefined'\n  End) as Status\nFROM (\n    SELECT\n        operatingStatus,time_sec,TIMESTAMP,\n        @rn := CASE WHEN (@prev <> operatingStatus) THEN @rn+1 ELSE @rn END AS rn,\n    \t@prev := operatingStatus\n    FROM (\n        SELECT operatingStatus,time_sec,TIMESTAMP\n        FROM WR_Daten\n        WHERE $__unixEpochFilter(time_sec)\n        ORDER BY ID ) AS a , \n        (SELECT @prev := -1, @rn := 0) AS vars \n) T1 Group BY rn ORDER BY `T1`.`time_sec` DESC"
    }
   ]
  },
  {
   "title": "Hausverbrauch (Tagesmittel, ausgewähltes Jahr)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochFrom()+hour(min(TIMESTAMP))*3600 as time_sec,\n  avg(HomeConsumptionSolar_kWh) AS PV,\n  avg(HomeConsumptionBat_kWh) AS Batterie,\n  avg(HomeConsumptionGrid_kWh) AS Netz,\n  avg(HomeConsumption_kWh) AS Gesamt,\n  1-LEAST(sum(HomeConsumptionGrid_kWh)/sum(HomeConsumption_kWh),1) AS Autarkie\nFROM aggregate_WR_Daten_hourly\nWHERE\n    DATE(TIMESTAMP) Between DATE(Date_format($__timeFrom(),\"%Y-%m-01\")) AND Last_DAY($__timeFrom())\nGROUP BY HOUR(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "PV Power (max Werte)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec+3600 as time_sec,\n  \"WR\" AS metric,\n  max(acPower) AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"PV Power\"  AS metric,\n  max(dcPowerPV) AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec+2*3600 as time_sec,\n  \"Bat Power\"  AS metric,\n  max(BatPowerEntLaden) AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n    time_sec+3*3600 as time_sec,\n  \"Bat Laden\"  AS metric,\n  max(BatPowerLaden) AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n    time_sec+4*3600 as time_sec,\n  \"Einspeisen\"  AS metric,\n  max(EinspeisenPower) AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"AVG (per day)\" as \"type\",\n  Date_format(TIMESTAMP,'%Y-%m') as \"Datum\",\n  avg(PV_kWh) AS \"PV\",\n  avg(BatLaden_kWh) AS \"Bat Laden\",\n  avg(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  avg(BatEntladen_kWh) AS \"Bat\",\n  avg(ac_kWh) AS \"WR\",\n  avg(Einspeisen_kWh) AS \"Einspeisen\",\n  avg(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  avg(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  avg(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  avg(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nunion all\nSELECT\n  \"Sum (timerange)\" as \"type\",\n  Date_format(min(TIMESTAMP),'%Y-%m') as \"Datum\",\n  sum(PV_kWh) AS \"PV\",\n  sum(BatLaden_kWh) AS \"Bat Laden\",\n  sum(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  sum(BatEntladen_kWh) AS \"Bat\",\n  sum(ac_kWh) AS \"WR\",\n  sum(Einspeisen_kWh) AS \"Einspeisen\",\n  sum(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  sum(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  sum(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  sum(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nunion all\nSELECT\n  \"Sum (overall)\" as \"type\",\n  Date_format(min(TIMESTAMP),'%Y') as \"Datum\",\n  sum(PV_kWh) AS \"PV\",\n  sum(BatLaden_kWh) AS \"Bat Laden\",\n  sum(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  sum(BatEntladen_kWh) AS \"Bat\",\n  sum(ac_kWh) AS \"WR\",\n  sum(Einspeisen_kWh) AS \"Einspeisen\",\n  sum(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  sum(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  sum(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  sum(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily"
    }
   ]
  },
  {
   "title": "Ertrag",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec AS time_sec,\n  sum(HomeConsumptionSolar_kWh) AS PV,\n  sum(HomeConsumptionBat_kWh) AS Batterie,\n  sum(Einspeisen_kWh) AS Einspeisen,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(ac_kWh) AS Eigenverbrauchsanteil,\n  sum(ac_kWh) AS \"WR output\",\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh) AS Eigenverbrauch,\n  sum(PV_kWh) as Ertrag\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec AS time_sec,\n  sum(DCsim)/1000 as Prognose\nFROM DWD_SIM_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(HomeConsumptionSolar_kWh) AS PV,\n  sum(HomeConsumptionBat_kWh) AS Batterie,\n  sum(HomeConsumptionGrid_kWh) AS Netz,\n  sum(HomeConsumption_kWh) AS Gesamt,\n  1-LEAST(sum(HomeConsumptionGrid_kWh)/sum(HomeConsumption_kWh),1) AS Autarkie\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Wirkungsgrade",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(ac_kWh)/sum(PV_kWh-BatLaden_kWh+BatEntladen_kWh) AS WR,\n  avg(BatTemperature) as \"Bat.Temperatur\",\n  sum(BatLaden_frei_kWh)/sum(BatLaden_kWh) AS \"Anteil int. Laden\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"Bat (Eigenverbrauch)\" AS metric,\n  sum(AktHomeConsumptionBat)/sum(acPower) AS value\nFROM WR_Daten\nWHERE\n  AktHomeConsumptionBat>1 and dcPowerPV<1 and $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Autarkie",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  1-sum(HomeConsumptionGrid_kWh)/sum(HomeConsumption_kWh) AS \"mit Bat\",\n  sum(HomeConsumptionSolar_kWh)/sum(HomeConsumption_kWh) AS \"ohne Bat\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Eigenverbrauch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(ac_kWh) AS \"mit Bat\",\n  sum(HomeConsumptionSolar_kWh)/sum(ac_kWh) AS \"ohne Bat\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Batterie Ladezustand",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  min(time_sec) as time,\n  COUNT(if(BatStateOfCharge > 99, 1, NULL))/60 as \"bei 100%\",\n  COUNT(if(BatStateOfCharge < 20, 1, NULL))/60 as \"unter 20%\",\n  COUNT(if(BatStateOfCharge <= 5, 1, NULL))/60 as \"unter 5%\"\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "PV Power",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  dcPowerPV as value,\n  \"PV Power\" as metric\nFROM WR_Daten\nWHERE $__unixEpochFilter(time_sec)\nORDER BY ID ASC"
    }
   ]
  },
  {
   "title": "Batterie Ent-/Laden",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  -(BatEntladen_kWh) as value,\n  \"Bat Entladen\" as metric\nFROM aggregate_WR_Daten_hourly\nWHERE $__unixEpochFilter(time_sec)"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  BatLaden_kWh as value,\n  \"Bat Laden\" as metric\nFROM aggregate_WR_Daten_hourly\nWHERE $__unixEpochFilter(time_sec)"
    }
   ]
  },
  {
   "title": "Autharkie",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 13, "w": 12, "x": 6, "y": 91 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  \"Autarkie\" AS metric,\n  Autarkie AS value\nFROM aggregate_WR_Daten_hourly\nWHERE\n  $__unixEpochFilter(time_sec)"
    }
   ]
  }
 ]
}