{
 "title": "04 Jahr",
 "description": "aktuelles Jahr",
 "tags": [ "PV" ],
 "time": { "from": "now/y", "to": "now/y" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "timeshift", "label": "Jahr", "query": "0y,1y,2y,3y,4y,5y,6y" },
   {
    "name": "current_time",
    "query": "Select concat(86400+2-TIME_TO_SEC(CURRENT_TIME()),'s')"
   },
   { "name": "grouping", "query": "${VAR_GROUPING}" }
  ]
 },
 "panels": [
  {
   "title": "Einspeisen",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT Date_format(TIMESTAMP,'%Y-%m') as Monat, Date_format(TIMESTAMP,'%Y-%m-%d') as \"Datum max\", Einspeisen_kWh as \"max Einspeisen (kWh)\"\nFrom  `aggregate_WR_Daten_daily`\nWhere $__unixEpochFilter(time_sec) AND Einspeisen_kWh in \n\t(SELECT max(Einspeisen_kWh)\n     FROM `aggregate_WR_Daten_daily`\n     Where $__unixEpochFilter(time_sec)\n     Group by year(TIMESTAMP),month(TIMESTAMP))\nGroup by year(TIMESTAMP),month(TIMESTAMP)"
    },
    {
     "rawSql": "SELECT Date_format(TIMESTAMP,'%Y-%m') as Monat, avg(Einspeisen_kWh) as \"mittel Einspeisen (kWh)\"\nFrom  `aggregate_WR_Daten_daily`\nWhere $__unixEpochFilter(time_sec)\nGroup by year(TIMESTAMP),month(TIMESTAMP)"
    },
    {
     "rawSql": "SELECT Date_format(TIMESTAMP,'%Y-%m') as Monat, Date_format(TIMESTAMP,'%Y-%m-%d') as \"Datum max (PV)\", PV_kWh as \"max PV (kWh)\"\nFrom  `aggregate_WR_Daten_daily`\nWhere $__unixEpochFilter(time_sec) AND PV_kWh in \n\t(SELECT max(PV_kWh)\n     FROM `aggregate_WR_Daten_daily`\n     Where $__unixEpochFilter(time_sec)\n     Group by year(TIMESTAMP),month(TIMESTAMP))\nGroup by year(TIMESTAMP),month(TIMESTAMP)"
    },
    {
     "rawSql": "SELECT Date_format(TIMESTAMP,'%Y-%m') as Monat, avg(PV_kWh) as \"mittel PV (kWh)\"\nFrom  `aggregate_WR_Daten_daily`\nWhere $__unixEpochFilter(time_sec)\nGroup by year(TIMESTAMP),month(TIMESTAMP)"
    },
    {
     "rawSql": "SELECT Date_format(TIMESTAMP,'%Y-%m') as Monat, Date_format(TIMESTAMP,'%Y-%m-%d') as \"Datum max (AC)\", PV_kWh as \"max AC (kWh)\"\nFrom  `aggregate_WR_Daten_daily`\nWhere $__unixEpochFilter(time_sec) AND ac_kWh in \n\t(SELECT max(ac_kWh)\n     FROM `aggregate_WR_Daten_daily`\n     Where $__unixEpochFilter(time_sec)\n     Group by year(TIMESTAMP),month(TIMESTAMP))\nGroup by year(TIMESTAMP),month(TIMESTAMP)"
    },
    {
     "rawSql": "SELECT Date_format(TIMESTAMP,'%Y-%m') as Monat, avg(ac_kWh) as \"mittel AC (kWh)\"\nFrom  `aggregate_WR_Daten_daily`\nWhere $__unixEpochFilter(time_sec)\nGroup by year(TIMESTAMP),month(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "Datum",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "SELECT\n  Year(TIMESTAMP) as value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Hausverbrauch (Tagesmittel, ausgewähltes Jahr)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochFrom()+hour(min(TIMESTAMP))*3600 as time_sec,\n  avg(HomeConsumptionSolar_kWh) AS PV,\n  avg(HomeConsumptionBat_kWh) AS Batterie,\n  avg(HomeConsumptionGrid_kWh) AS Netz,\n  avg(HomeConsumption_kWh) AS Gsamt,\n  (avg(HomeConsumptionSolar_kWh)+avg(HomeConsumptionBat_kWh))/avg(HomeConsumption_kWh) AS Autarkie\nFROM aggregate_WR_Daten_hourly\nWHERE\n  DATE(TIMESTAMP) Between DATE(Date_format($__timeFrom(),\"%Y-01-01\")) AND DATE(Date_format($__timeFrom(),\"%Y-12-31\"))\nGROUP BY HOUR(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"AVG (per day)\" as \"type\",\n  year(TIMESTAMP) as \"Datum\",\n  avg(PV_kWh) AS \"PV\",\n  avg(BatLaden_kWh) AS \"Bat Laden\",\n  avg(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  avg(BatEntladen_kWh) AS \"Bat\",\n  avg(ac_kWh) AS \"WR\",\n  avg(Einspeisen_kWh) AS \"Einspeisen\",\n  avg(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  avg(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  avg(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  avg(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nunion all\nSELECT\n  \"Sum (timerange)\" as \"type\",\n  year(TIMESTAMP) as \"Datum\",\n  sum(PV_kWh) AS \"PV\",\n  sum(BatLaden_kWh) AS \"Bat Laden\",\n  sum(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  sum(BatEntladen_kWh) AS \"Bat\",\n  sum(ac_kWh) AS \"WR\",\n  sum(Einspeisen_kWh) AS \"Einspeisen\",\n  sum(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  sum(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  sum(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  sum(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nunion all\nSELECT\n  \"Sum (overall)\" as \"type\",\n  year(TIMESTAMP) as \"Datum\",\n  sum(PV_kWh) AS \"PV\",\n  sum(BatLaden_kWh) AS \"Bat Laden\",\n  sum(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  sum(BatEntladen_kWh) AS \"Bat\",\n  sum(ac_kWh) AS \"WR\",\n  sum(Einspeisen_kWh) AS \"Einspeisen\",\n  sum(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  sum(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  sum(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  sum(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily"
    }
   ]
  },
  {
   "title": "Ertrag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(HomeConsumptionSolar_kWh) AS PV,\n  sum(HomeConsumptionBat_kWh) AS Batterie,\n  sum(Einspeisen_kWh) AS Einspeisen,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(ac_kWh) AS Eigenverbrauchsanteil,\n  sum(ac_kWh) AS \"WR output\",\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh) AS Eigenverbrauch,\n  sum(PV_kWh) as Ertrag\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(DCsim)/1000 as Prognose\nFROM DWD_SIM_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(HomeConsumptionSolar_kWh) AS PV,\n  sum(HomeConsumptionBat_kWh) AS Batterie,\n  sum(HomeConsumptionGrid_kWh) AS Netz,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(HomeConsumption_kWh) AS Autarkie,\n  sum(HomeConsumption_kWh) AS gesamt\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Autarkie Rechnungen",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none", "label": "Anzahl Tage" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  \"Autarkie\" AS metric,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(HomeConsumption_kWh) AS value\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"90%\" AS metric,\n  count(*) AS value\nFROM aggregate_WR_Daten_daily\nWHERE\n  Autarkie >= 0.9 AND $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"80%\" AS metric,\n  count(*) AS value\nFROM aggregate_WR_Daten_daily\nWHERE\n  Autarkie >= 0.8 AND $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"70%\" AS metric,\n  count(*) AS value\nFROM aggregate_WR_Daten_daily\nWHERE\n  Autarkie >= 0.7 AND $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"50%\" AS metric,\n  count(*) AS value\nFROM aggregate_WR_Daten_daily\nWHERE\n  Autarkie >= 0.5 AND $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"95%\" AS metric,\n  count(*) AS value\nFROM aggregate_WR_Daten_daily\nWHERE\n  Autarkie >= 0.95 AND $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  T1.time_sec as time_sec,\n  sum(T1.cycles) as value,\n  \"Lade Zyklen\" as metrics\nFROM (\n  SELECT\n    time_sec,\n    timestamp,\n    max(ChargeCycles)-min(ChargeCycles) as cycles\n  FROM WR_Daten\n  WHERE\n    $__unixEpochFilter(time_sec)\n  GRoup BY to_days(timestamp)\n  )T1\nWhere cycles<30\nGroup by $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(BatLaden_kWh) as \"Bat Laden\",\n  sum(BatEntladen_kWh) as \"Bat Entnahme\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Wirkungsgrade",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(ac_kWh)/sum(PV_kWh-BatLaden_kWh+BatEntladen_kWh) AS \"WR\",\n  sum(BatEntladen_kWh)/sum(BatLaden_kWh) AS \"Bat (DC/DC)\",\n  sum(HomeConsumptionBat_kWh)/sum(BatLaden_kWh) AS \"Bat (incl WR)\",\n  avg(BatTemperature) as \"Bat.Temperatur\",\n  sum(BatLaden_frei_kWh)/sum(BatLaden_kWh) AS \"Anteil int. Laden\",\n  sum(BatLaden_kWh-BatEntladen_kWh)/sum(PV_kWh) AS VerlustAnteil\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec) and DATE(TIMESTAMP) < curdate()\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"Bat (Eigenverbrauch)\" AS metric,\n  sum(HomeConsumptionBat_kWh)/sum(ac_kWh) AS value\nFROM aggregate_WR_Daten_hourly\nWHERE\n  HomeConsumptionBat_kWh>0 and PV_kWh=0 and $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(BatEntladen_kWh)/sum(BatLaden_kWh)*sum(if(PV_kWh=0 AND BatEntLaden_kWh is not null,ac_kWh,0))/sum(if(PV_kWh=0 AND BatEntLaden_kWh is not null,BatEntLaden_kWh,0)) AS \"Bat (DC/DC/AC)\",\n  sum(BatEntladen_kWh)/sum(BatLaden_kWh-BatLaden_frei_kWh)*sum(if(PV_kWh=0 AND BatEntLaden_kWh is not null,ac_kWh,0))/sum(if(PV_kWh=0 AND BatEntLaden_kWh is not null,BatEntLaden_kWh,0)) AS \"Bat (Virt) (DC/DC/AC)\"\nFROM aggregate_WR_Daten_hourly\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Temperaturabhängigkeit Batteriewirkungsgrad (DC/DC)",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(BatEntladen_kWh)*100/sum(BatLaden_kWh) AS eff,\n  avg(BatTemperature) as x_value\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec) and DATE(TIMESTAMP) < curdate()\nGROUP BY $grouping\nOrder BY x_value"
    }
   ]
  },
  {
   "title": "Autarkie",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(HomeConsumption_kWh) AS \"mit Bat\",\n  sum(HomeConsumptionSolar_kWh)/sum(HomeConsumption_kWh) AS \"ohne Bat\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Eigenverbrauch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  \"mit Bat\" AS metric,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(ac_kWh) AS \"mit Bat\",\n  sum(HomeConsumptionSolar_kWh)/sum(ac_kWh) AS \"ohne Bat\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Batterie Ladezustand (Tagesmittel)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  min(T1.time_sec) as time_sec,\n  avg(T1.val1) as \"bei 100%\",\n  avg(T1.val2) as \"unter 20%\",\n  avg(T1.val3) as \"unter 5%\"\nFROM(\n  SELECT\n    TIMESTAMP,\n    min(time_sec) as time_sec,\n    COUNT(if(BatStateOfCharge > 99, 1, NULL))/60 as val1,\n    COUNT(if(BatStateOfCharge < 20, 1, NULL))/60 as val2,\n    COUNT(if(BatStateOfCharge <= 5, 1, NULL))/60 as val3\n  FROM WR_Daten\n  WHERE  $__unixEpochFilter(time_sec)\n  Group BY to_days(TIMESTAMP))T1\nGROUP BY $grouping\n"
    }
   ]
  },
  {
   "title": "PV Power",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  PV_kWh as value,\n  \"PV Power\" as metric\nFROM aggregate_WR_Daten_hourly\nWHERE $__unixEpochFilter(time_sec)"
    }
   ]
  },
  {
   "title": "Batterie Ent-/Laden",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  -(BatEntladen_kWh) as value,\n  \"Bat Entladen\" as metric\nFROM aggregate_WR_Daten_hourly\nWHERE $__unixEpochFilter(time_sec)"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  BatLaden_kWh as value,\n  \"Bat Laden\" as metric\nFROM aggregate_WR_Daten_hourly\nWHERE $__unixEpochFilter(time_sec)"
    }
   ]
  },
  {
   "title": "Autarkie",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 78 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  \"Autarkie\" AS metric,\n  Autarkie AS value\nFROM aggregate_WR_Daten_hourly\nWHERE\n  $__unixEpochFilter(time_sec)"
    }
   ]
  }
 ]
}