{
 "title": "05 Jahresübersicht",
 "description": "aktuelles Jahr",
 "tags": [ "PV" ],
 "time": { "from": "now-20y/y", "to": "now/y" },
 "refresh": "1d",
 "templating": {
  "list": [
   { "name": "timeshift", "label": "Jahr", "query": "0y,1y,2y,3y,4y,5y,6y" },
   {
    "name": "current_time",
    "query": "Select concat(TIME_TO_SEC(CURTIME()),'s')"
   },
   { "name": "grouping", "query": "${VAR_GROUPING}" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"AVG (per day)\" as \"type\",\n  concat(\"seit \",year(TIMESTAMP)) as \"Datum\",\n  avg(PV_kWh) AS \"PV\",\n  avg(BatLaden_kWh) AS \"Bat Laden\",\n  avg(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  avg(BatEntladen_kWh) AS \"Bat\",\n  avg(ac_kWh) AS \"WR\",\n  avg(Einspeisen_kWh) AS \"Einspeisen\",\n  avg(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  avg(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  avg(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  avg(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nunion all\nSELECT\n  \"Sum (overall)\" as \"type\",\n  concat(\"seit \",year(TIMESTAMP)) as \"Datum\",\n  sum(PV_kWh) AS \"PV\",\n  sum(BatLaden_kWh) AS \"Bat Laden\",\n  sum(BatLaden_frei_kWh) AS \"Bat Laden (frei)\",\n  sum(BatEntladen_kWh) AS \"Bat\",\n  sum(ac_kWh) AS \"WR\",\n  sum(Einspeisen_kWh) AS \"Einspeisen\",\n  sum(HomeConsumption_kWh) AS \"Hausverbrauch\",\n  sum(HomeConsumptionSolar_kWh) AS \"Hausverbrauch PV\",\n  sum(HomeConsumptionBat_kWh) AS \"Hausverbrauch Bat\",\n  sum(HomeConsumptionGrid_kWh) AS \"Hausverbrauch Netz\"\nFROM aggregate_WR_Daten_daily"
    }
   ]
  },
  {
   "title": "Ertrag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(HomeConsumptionSolar_kWh) AS PV,\n  sum(HomeConsumptionBat_kWh) AS Batterie,\n  sum(Einspeisen_kWh) AS Einspeisen,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(ac_kWh) AS Eigenverbrauchsanteil,\n  sum(ac_kWh) AS \"WR output\",\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh) AS Eigenverbrauch,\n  sum(PV_kWh) as Ertrag\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(DCsim)/1000 as Prognose\nFROM DWD_SIM_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(HomeConsumptionSolar_kWh) AS PV,\n  sum(HomeConsumptionBat_kWh) AS Batterie,\n  sum(HomeConsumptionGrid_kWh) AS Netz,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(HomeConsumption_kWh) AS Autarkie,\n  sum(HomeConsumption_kWh) AS gesamt\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Wirkungsgrade",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(ac_kWh)/sum(PV_kWh-BatLaden_kWh+BatEntladen_kWh) AS \"WR\",\n  sum(BatEntladen_kWh)/sum(BatLaden_kWh) AS \"Bat (DC/DC)\",\n  sum(HomeConsumptionBat_kWh)/sum(BatLaden_kWh) AS \"Bat (incl WR)\",\n  avg(BatTemperature) as \"Bat.Temperatur\",\n  sum(BatLaden_frei_kWh)/sum(BatLaden_kWh) AS \"Anteil int. Laden\",\n  sum(BatLaden_kWh-BatEntladen_kWh)/sum(PV_kWh) AS VerlustAnteil\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec) and DATE(TIMESTAMP) < curdate()\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"Bat (Eigenverbrauch)\" AS metric,\n  sum(HomeConsumptionBat_kWh)/sum(ac_kWh) AS value\nFROM aggregate_WR_Daten_hourly\nWHERE\n  HomeConsumptionBat_kWh>0 and PV_kWh=0 and $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(BatEntladen_kWh)/sum(BatLaden_kWh)*sum(if(PV_kWh=0 AND BatEntLaden_kWh is not null,ac_kWh,0))/sum(if(PV_kWh=0 AND BatEntLaden_kWh is not null,BatEntLaden_kWh,0)) AS \"Bat (DC/DC/AC)\",\n  sum(BatEntladen_kWh)/sum(BatLaden_kWh-BatLaden_frei_kWh)*sum(if(PV_kWh=0 AND BatEntLaden_kWh is not null,ac_kWh,0))/sum(if(PV_kWh=0 AND BatEntLaden_kWh is not null,BatEntLaden_kWh,0)) AS \"Bat (Virt) (DC/DC/AC)\"\nFROM aggregate_WR_Daten_hourly\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Autarkie",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(HomeConsumption_kWh) AS \"mit Bat\",\n  sum(HomeConsumptionSolar_kWh)/sum(HomeConsumption_kWh) AS \"ohne Bat\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Eigenverbrauch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(ac_kWh) AS \"mit Bat\",\n  sum(HomeConsumptionSolar_kWh)/sum(ac_kWh) AS \"ohne Bat\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Autarkie Rechnungen",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none", "label": "Anzahl Tage" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  \"Autarkie\" AS metric,\n  1-LEAST(sum(HomeConsumptionGrid_kWh)/sum(HomeConsumption_kWh),1) AS value\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"90%\" AS metric,\n  count(*) AS value\nFROM aggregate_WR_Daten_daily\nWHERE\n  HomeConsumptionGrid_kWh/HomeConsumption_kWh<0.1 AND $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"80%\" AS metric,\n  count(*) AS value\nFROM aggregate_WR_Daten_daily\nWHERE\n  HomeConsumptionGrid_kWh/HomeConsumption_kWh<0.2 AND $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"70%\" AS metric,\n  count(*) AS value\nFROM aggregate_WR_Daten_daily\nWHERE\n  HomeConsumptionGrid_kWh/HomeConsumption_kWh<0.3 AND $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"50%\" AS metric,\n  count(*) AS value\nFROM aggregate_WR_Daten_daily\nWHERE\n  HomeConsumptionGrid_kWh/HomeConsumption_kWh<0.5 AND $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"95%\" AS metric,\n  count(*) AS value\nFROM aggregate_WR_Daten_daily\nWHERE\n  HomeConsumptionGrid_kWh/HomeConsumption_kWh<0.05 AND $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  max(ChargeCycles)-min(ChargeCycles) as \"Lade Zyklen\",\n  sum(BatLaden_kWh) as \"Bat Laden\",\n  sum(BatEntladen_kWh) as \"Bat Entnahme\"\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY $grouping"
    }
   ]
  },
  {
   "title": "Temperaturabhängigkeit Batteriewirkungsgrad (DC/DC)",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 10, "x": 7, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(BatEntladen_kWh)*100/sum(BatLaden_kWh) AS eff,\n  avg(BatTemperature) as x_value\nFROM aggregate_WR_Daten_daily\nWHERE\n  $__unixEpochFilter(time_sec) and DATE(TIMESTAMP) < subdate(curdate(), (day(curdate())-1))\nGROUP BY year(TIMESTAMP), month(TIMESTAMP)\nOrder BY x_value"
    }
   ]
  },
  {
   "title": "Batterie Ladezustand (Tagesmittel)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  min(T1.time_sec) as time_sec,\n  avg(T1.val1) as \"bei 100%\",\n  avg(T1.val2) as \"unter 20%\",\n  avg(T1.val3) as \"unter 5%\"\nFROM(\n  SELECT\n    TIMESTAMP,\n    min(time_sec) as time_sec,\n    COUNT(if(BatStateOfCharge > 99, 1, NULL))/60 as val1,\n    COUNT(if(BatStateOfCharge < 20, 1, NULL))/60 as val2,\n    COUNT(if(BatStateOfCharge <= 5, 1, NULL))/60 as val3\n  FROM WR_Daten\n  WHERE  $__unixEpochFilter(time_sec)\n  Group BY to_days(TIMESTAMP))T1\nGROUP BY $grouping\n"
    }
   ]
  }
 ]
}