{
 "title": "06 Jahresvergleich",
 "tags": [ "PV" ],
 "time": { "from": "now/y", "to": "now/y" },
 "panels": [
  { "title": "Absolute Werte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PV-Ertrag",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(T1.TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  \"Mittel\" AS metric,\n  avg(T1.value) as value\nFROM(\nSELECT\n  TIMESTAMP,\n  sum(PV_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)) T1\nGROUP BY month(T1.TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  convert(YEAR(TIMESTAMP), char) AS metric,\n  sum(PV_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "PV-Ertrag",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "kWh/kWp" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(T1.TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  \"Mittel\" AS metric,\n  avg(T1.value)/7.68 as value\nFROM(\nSELECT\n  TIMESTAMP,\n  sum(PV_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)) T1\nGROUP BY month(T1.TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  convert(YEAR(TIMESTAMP), char) AS metric,\n  sum(PV_kWh)/7.68 AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "WR-Output",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(T1.TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  \"Mittel\" AS metric,\n  avg(T1.value) as value\nFROM(\nSELECT\n  TIMESTAMP,\n  sum(ac_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)) T1\nGROUP BY month(T1.TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  convert(YEAR(TIMESTAMP), char) AS metric,\n  sum(ac_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "WR-Output",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "kWh/kWp" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(T1.TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  \"Mittel\" AS metric,\n  avg(T1.value)/7.68 as value\nFROM(\nSELECT\n  TIMESTAMP,\n  sum(ac_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)) T1\nGROUP BY month(T1.TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  convert(YEAR(TIMESTAMP), char) AS metric,\n  sum(ac_kWh)/7.68 AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "Einspeisen",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(T1.TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  \"Mittel\" AS metric,\n  avg(T1.value) as value\nFROM(\nSELECT\n  TIMESTAMP,\n  sum(Einspeisen_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)) T1\nGROUP BY month(T1.TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  convert(YEAR(TIMESTAMP), char) AS metric,\n  sum(Einspeisen_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(T1.TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  \"Mittel\" AS metric,\n  avg(T1.value) as value\nFROM(\nSELECT\n  TIMESTAMP,\n  sum(HomeConsumption_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)) T1\nGROUP BY month(T1.TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  convert(YEAR(TIMESTAMP), char) AS metric,\n  sum(HomeConsumption_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "Hausverbrauch - Solar",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(T1.TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  \"Mittel\" AS metric,\n  avg(T1.value) as value\nFROM(\nSELECT\n  TIMESTAMP,\n  sum(HomeConsumptionSolar_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)) T1\nGROUP BY month(T1.TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  convert(YEAR(TIMESTAMP), char) AS metric,\n  sum(HomeConsumptionSolar_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "Hausverbrauch - Batterie",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(T1.TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  \"Mittel\" AS metric,\n  avg(T1.value) as value\nFROM(\nSELECT\n  TIMESTAMP,\n  sum(HomeConsumptionBat_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)) T1\nGROUP BY month(T1.TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  convert(YEAR(TIMESTAMP), char) AS metric,\n  sum(HomeConsumptionBat_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "Hausverbrauch - Solar&Batterie",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(T1.TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  \"Mittel\" AS metric,\n  avg(T1.value) as value\nFROM(\nSELECT\n  TIMESTAMP,\n  sum(HomeConsumptionBat_kWh+HomeConsumptionSolar_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)) T1\nGROUP BY month(T1.TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  convert(YEAR(TIMESTAMP), char) AS metric,\n  sum(HomeConsumptionBat_kWh+HomeConsumptionSolar_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "Hausverbrauch - Netz",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(T1.TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  \"Mittel\" AS metric,\n  avg(T1.value) as value\nFROM(\nSELECT\n  TIMESTAMP,\n  sum(HomeConsumptionGrid_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)) T1\nGROUP BY month(T1.TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  convert(YEAR(TIMESTAMP), char) AS metric,\n  sum(HomeConsumptionGrid_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)"
    }
   ]
  },
  { "title": "Relative Werte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Autarkie incl Bat",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  \"Mittel\" AS metric,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(HomeConsumption_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY month(TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  convert(year(TIMESTAMP), char) AS metric,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(HomeConsumption_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY Year(TIMESTAMP),month(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "Autarkie ohne Bat",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  \"Mittel\" AS metric,\n  sum(HomeConsumptionSolar_kWh)/sum(HomeConsumption_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY month(TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  convert(YEAR(TIMESTAMP), char) AS metric,\n  sum(HomeConsumptionSolar_kWh)/sum(HomeConsumption_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY Year(TIMESTAMP), month(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "EigenverbrauchAnteil",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  \"Mittel\" AS metric,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(ac_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY Month(TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  convert(YEAR(TIMESTAMP), char) AS metric,\n  sum(HomeConsumptionSolar_kWh+HomeConsumptionBat_kWh)/sum(ac_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP), Month(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "EigenverbrauchAnteil(ohne Bat)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  \"Mittel\" AS metric,\n  sum(HomeConsumptionSolar_kWh)/sum(ac_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY month(TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  convert(YEAR(TIMESTAMP), char) AS metric,\n  sum(HomeConsumptionSolar_kWh)/sum(ac_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "Wirkungsgrad Bat-Ladung",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  \"Mittel\" AS metric,\n  sum(BatEntladen_kWh)/sum(BatLaden_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY month(TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  convert(YEAR(TIMESTAMP), char) AS metric,\n  sum(BatEntladen_kWh)/sum(BatLaden_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)"
    }
   ]
  },
  {
   "title": "Anteil Kostenfreier Bat-Ladung",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  \"Mittel\" AS metric,\n  sum(BatLaden_frei_kWh)/sum(BatLaden_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY month(TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(STR_TO_DATE(concat(YEAR(now()),'-',Month(TIMESTAMP),'-01'),'%Y-%c-%d')) as time,\n  convert(YEAR(TIMESTAMP), char) AS metric,\n  sum(BatLaden_frei_kWh)/sum(BatLaden_kWh) AS value\nFROM aggregate_WR_Daten_daily\nGROUP BY YEAR(TIMESTAMP),month(TIMESTAMP)"
    }
   ]
  }
 ]
}