{
 "title": "07 Prognose - Quality",
 "tags": [ "PV" ],
 "time": { "from": "now-3d/d", "to": "now+10d/d" },
 "templating": {
  "list": [
   { "name": "timeshift", "query": "0d,1d,2d,3d,4d,5d" },
   { "name": "PVarea", "query": "${VAR_PVAREA}" },
   { "name": "Wirkgrad", "query": "${VAR_WIRKGRAD}" },
   {
    "name": "current_time",
    "query": "Select concat(TIME_TO_SEC(CURTIME()),'s')"
   },
   { "name": "fitmethod", "label": "Fit-Methode", "query": "Faktor,LeastSQR" },
   {
    "name": "remaining_days",
    "query": "Select concat('0s+',365-DAYOFYEAR(CURDATE()),'d')"
   }
  ]
 },
 "panels": [
  {
   "title": "fit-quality (lowest is best)",
   "type": "bargauge",
   "description": "calc by reduced chi-square",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\nT2.time_sec as time_sec,\nT2.DCSim/T2.N as DCSim,\nT2.LeastSQR/T2.N as LeastSQR,\nT2.Faktor/T2.N as Faktor\nfrom(\n\tselect\n\tT1.time_sec as time_sec,\n\tcount(*) as N,\n\tsum(pow(T1.DCPower - T1.DCSim,2)/T1.DCPower) as DCSim,\n\tsum(pow(T1.DCPower - T1.LeastSQR,2)/T1.DCPower) as LeastSQR,\n\tsum(pow(T1.DCPower - T1.Faktor,2)/T1.DCPower) as Faktor\n\tfrom (\n\t\tselect \n\t\taggregate_WR_Daten_hourly.time_sec AS time_sec,\n\t\taggregate_WR_Daten_hourly.PV_kWh*1000 AS DCPower,\n\t\tDWD_SIM_Daten.DCSim AS DCSim,\n\t\tDWD_SIM_Daten.Rad1Energy * DWD_SIM_Rad_factor.LeastSQR AS LeastSQR,\n\t\tDWD_SIM_Daten.Rad1Energy * DWD_SIM_Rad_factor.Faktor AS Faktor\n\t\tfrom (aggregate_WR_Daten_hourly\n\t\t\tjoin DWD_SIM_Daten on ( TIMESTAMPADD(HOUR,1,aggregate_WR_Daten_hourly.TIMESTAMP) = DWD_SIM_Daten.TIMESTAMP)\n\t\t\tjoin DWD_SIM_Rad_factor on ( DWD_SIM_Rad_factor.month = month(DWD_SIM_Daten.TIMESTAMP))\n\t\t\t)\n\t\twhere DWD_SIM_Daten.Rad1wh > 0 and aggregate_WR_Daten_hourly.time_sec >= (select DWD_SIM_Daten.time_sec from DWD_SIM_Daten order by DWD_SIM_Daten.time_sec limit 1) - 3601) T1\n\twhere T1.DCPower > 0\n) T2"
    }
   ]
  },
  {
   "title": "Abweichung DCSim",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "select \n\t\taggregate_WR_Daten_hourly.time_sec as time_sec,\n\t\tDWD_SIM_Daten.DCSim - aggregate_WR_Daten_hourly.PV_kWh*1000 AS DCSim\n\t\tfrom (aggregate_WR_Daten_hourly\n\t\t\tjoin DWD_SIM_Daten on ( TIMESTAMPADD(HOUR,1,aggregate_WR_Daten_hourly.TIMESTAMP) = DWD_SIM_Daten.TIMESTAMP)\n\t\t\t)\n\t\twhere (aggregate_WR_Daten_hourly.PV_kWh>0.001 or DWD_SIM_Daten.DCSim >1) and aggregate_WR_Daten_hourly.time_sec >= (select DWD_SIM_Daten.time_sec from DWD_SIM_Daten order by DWD_SIM_Daten.time_sec limit 1) - 3601"
    }
   ]
  },
  {
   "title": "Abweichung $fitmethod",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "select \n\t\taggregate_WR_Daten_hourly.time_sec as time_sec,\n\t\tDWD_SIM_Daten.Rad1Energy * DWD_SIM_Rad_factor.$fitmethod - aggregate_WR_Daten_hourly.PV_kWh*1000 AS DCFaktor\n\t\tfrom (aggregate_WR_Daten_hourly\n\t\t\tjoin DWD_SIM_Daten on ( TIMESTAMPADD(HOUR,1,aggregate_WR_Daten_hourly.TIMESTAMP) = DWD_SIM_Daten.TIMESTAMP)\n\t\t\tjoin DWD_SIM_Rad_factor on ( DWD_SIM_Rad_factor.month = month(DWD_SIM_Daten.TIMESTAMP))\n\t\t\t)\n\t\twhere (aggregate_WR_Daten_hourly.PV_kWh>0.001 or DWD_SIM_Daten.Rad1Energy >1) and aggregate_WR_Daten_hourly.time_sec >= (select DWD_SIM_Daten.time_sec from DWD_SIM_Daten order by DWD_SIM_Daten.time_sec limit 1) - 3601"
    }
   ]
  },
  {
   "title": "DC-Values",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec+3600 as time_sec,\n  \"PV Power\"  AS metric,\n  PV_kWh*1000 as value\nFROM aggregate_WR_Daten_hourly\nWHERE\n  $__unixEpochFilter(time_sec+3600)"
    },
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  Rad1Energy*DWD_SIM_Rad_factor.$fitmethod as value,\n  \"Prognose\" as metric\nFROM DWD_SIM_Daten\nLeft Join DWD_SIM_Rad_factor on month=month(TIMESTAMP)\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    },
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  DCSim,\n  Rad1Energy\nFROM DWD_SIM_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "Voltage/Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec+3600 AS \"time\",\n  dc1Voltage,\n  dc2Voltage,\n  dc1Current,\n  dc2Current\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    },
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  VmpSIM,\n  ImpSIM\nFROM DWD_SIM_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "AC-Values",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec+3600 as time_sec,\n  ac_kWh*1000 as \"AC Power\"\nFROM aggregate_WR_Daten_hourly\nWHERE\n  $__unixEpochFilter(time_sec+3600)"
    },
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  ACSim\nFROM DWD_SIM_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "Faktoren: Rad1Energy to PVpower",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none", "label": "Faktor" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATE(concat(YEAR(CURDATE()),'-',month,'-01')) as time,\n  LeastSQR,\n  Faktor\nFROM DWD_SIM_Rad_factor"
    }
   ]
  }
 ]
}