{
 "title": "08 Gewinne",
 "tags": [ "PV" ],
 "time": { "from": "now-32d/d", "to": "now/d" },
 "templating": {
  "list": [
   { "name": "Steuersatz", "label": "Stuersatz", "query": "0.2,0.25,0.3,0.35,0.4" },
   { "name": "zinssatz", "label": "GuthabenZins", "query": "0.02,0.01,0.05" }
  ]
 },
 "panels": [
  {
   "title": "Einnahmen/Steuern/Gewinn(täglich)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  Verkauf,\n  Ersparnis,\n  -MWST as MWST,\n  IF (SteuerlGewinn>(Abschreibung+MWST), (Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0) AS SteuerGewinn,\n  IF (SteuerlGewinn>Abschreibung+MWST, (Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0)+Verkauf+Ersparnis-MWST-Abschreibung AS Gewinn,\n  IF (SteuerlGewinn>Abschreibung+MWST, (Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0)+Verkauf-BezugKosten-MWST-Abschreibung AS GesÜberschuss\nFROM Gewinne_Verlust\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    },
    {
     "rawSql": "SELECT\n  Gewinne_Verlust.time_sec AS time_sec,\n  (IF (Gewinne_Verlust.SteuerlGewinn>Gewinne_Verlust.Abschreibung+Gewinne_Verlust.MWST, (Gewinne_Verlust.Abschreibung+Gewinne_Verlust.MWST-Gewinne_Verlust.SteuerlGewinn)*$Steuersatz,0)+Gewinne_Verlust.Verkauf-Gewinne_Verlust.BezugKosten-Gewinne_Verlust.MWST-Gewinne_Verlust.Abschreibung) \n  -(IF (Gewinne_Verlust_PVonly.SteuerlGewinn>Gewinne_Verlust_PVonly.Abschreibung+Gewinne_Verlust_PVonly.MWST, (Gewinne_Verlust_PVonly.Abschreibung+Gewinne_Verlust_PVonly.MWST-Gewinne_Verlust_PVonly.SteuerlGewinn)*$Steuersatz,0)+Gewinne_Verlust_PVonly.Verkauf-Gewinne_Verlust_PVonly.BezugKosten-Gewinne_Verlust_PVonly.MWST-Gewinne_Verlust_PVonly.Abschreibung )\n  AS BatVorteil\nFROM Gewinne_Verlust\nJoin Gewinne_Verlust_PVonly on Gewinne_Verlust.time_sec=Gewinne_Verlust_PVonly.time_sec\nWHERE\n    $__unixEpochFilter(Gewinne_Verlust.time_sec)\nORDER BY Gewinne_Verlust.time_sec"
    }
   ]
  },
  {
   "title": "Einnahmen/Steuern/Gewinn(monatlich)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "currencyEUR", "label": "pro Tag" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(Verkauf)/max(day(TIMESTAMP)) as Verkauf,\n  sum(Ersparnis)/max(day(TIMESTAMP)) as Ersparnis,\n  -sum(MWST)/max(day(TIMESTAMP)) as MWST,\n  IF(sum(SteuerlGewinn)>sum(Abschreibung+MWST),sum(Abschreibung+MWST-SteuerlGewinn)*$Steuersatz/max(day(TIMESTAMP)),0) as SteuerGewinn,\n  (sum(Verkauf+Ersparnis-MWST-Abschreibung)+  IF(sum(SteuerlGewinn)>sum(Abschreibung+MWST),sum(Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0))/max(day(TIMESTAMP)) as Gewinn,\n  (sum(Verkauf-BezugKosten-MWST-Abschreibung)+  IF(sum(SteuerlGewinn)>sum(Abschreibung+MWST),sum(Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0))/max(day(TIMESTAMP)) as GesÜberschuss,\n  -sum(Abschreibung)/max(day(TIMESTAMP)) as Abschreibung\nFROM Gewinne_Verlust\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY year(TIMESTAMP),month(TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n  Gewinne_Verlust.time_sec AS \"time\",\n  \"BatVorteil\" as metrics,\n  (IF (sum(Gewinne_Verlust.SteuerlGewinn)>sum(Gewinne_Verlust.Abschreibung+Gewinne_Verlust.MWST), (sum(Gewinne_Verlust.Abschreibung+Gewinne_Verlust.MWST)-sum(Gewinne_Verlust.SteuerlGewinn))*$Steuersatz,0)+sum(Gewinne_Verlust.Verkauf-Gewinne_Verlust.BezugKosten-Gewinne_Verlust.MWST-Gewinne_Verlust.Abschreibung) \n  -(IF (sum(Gewinne_Verlust_PVonly.SteuerlGewinn)>sum(Gewinne_Verlust_PVonly.Abschreibung+Gewinne_Verlust_PVonly.MWST), (sum(Gewinne_Verlust_PVonly.Abschreibung+Gewinne_Verlust_PVonly.MWST)-sum(Gewinne_Verlust_PVonly.SteuerlGewinn))*$Steuersatz,0)+sum(Gewinne_Verlust_PVonly.Verkauf-Gewinne_Verlust_PVonly.BezugKosten-Gewinne_Verlust_PVonly.MWST-Gewinne_Verlust_PVonly.Abschreibung) ))/max(day(Gewinne_Verlust.TIMESTAMP))\n  AS value\nFROM Gewinne_Verlust\nJoin Gewinne_Verlust_PVonly on Gewinne_Verlust.time_sec=Gewinne_Verlust_PVonly.time_sec\nWHERE\n    $__unixEpochFilter(Gewinne_Verlust.time_sec)\nGROUP BY year(Gewinne_Verlust.TIMESTAMP),month(Gewinne_Verlust.TIMESTAMP)\n"
    }
   ]
  },
  {
   "title": "Einnahmen/Steuern/Gewinn(jährlich)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "currencyEUR", "label": "pro Tag" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(Verkauf)/max(DAYOFYEAR(TIMESTAMP)) as Verkauf,\n  sum(Ersparnis)/max(DAYOFYEAR(TIMESTAMP)) as Ersparnis,\n  -sum(MWST)/max(DAYOFYEAR(TIMESTAMP)) as MWST,\n  IF(sum(SteuerlGewinn)>sum(Abschreibung+MWST),sum(Abschreibung+MWST-SteuerlGewinn)*$Steuersatz/max(DAYOFYEAR(TIMESTAMP)),0) as SteuerGewinn,\n  (sum(Verkauf+Ersparnis-MWST-Abschreibung)+  IF(sum(SteuerlGewinn)>sum(Abschreibung+MWST),sum(Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0))/max(DAYOFYEAR(TIMESTAMP)) as Gewinn,\n  (sum(Verkauf-BezugKosten-MWST-Abschreibung)+  IF(sum(SteuerlGewinn)>sum(Abschreibung+MWST),sum(Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0))/max(DAYOFYEAR(TIMESTAMP)) as GesÜberschuss,\n  -sum(Abschreibung)/max(DAYOFYEAR(TIMESTAMP)) as Abschreibung\nFROM Gewinne_Verlust\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY year(TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n  Gewinne_Verlust.time_sec AS \"time\",\n  \"BatVorteil\" as metrics,\n  (IF (sum(Gewinne_Verlust.SteuerlGewinn)>sum(Gewinne_Verlust.Abschreibung+Gewinne_Verlust.MWST), (sum(Gewinne_Verlust.Abschreibung+Gewinne_Verlust.MWST)-sum(Gewinne_Verlust.SteuerlGewinn))*$Steuersatz,0)+sum(Gewinne_Verlust.Verkauf-Gewinne_Verlust.BezugKosten-Gewinne_Verlust.MWST-Gewinne_Verlust.Abschreibung) \n  -(IF (sum(Gewinne_Verlust_PVonly.SteuerlGewinn)>sum(Gewinne_Verlust_PVonly.Abschreibung+Gewinne_Verlust_PVonly.MWST), (sum(Gewinne_Verlust_PVonly.Abschreibung+Gewinne_Verlust_PVonly.MWST)-sum(Gewinne_Verlust_PVonly.SteuerlGewinn))*$Steuersatz,0)+sum(Gewinne_Verlust_PVonly.Verkauf-Gewinne_Verlust_PVonly.BezugKosten-Gewinne_Verlust_PVonly.MWST-Gewinne_Verlust_PVonly.Abschreibung) ))/max(DAYOFYEAR(Gewinne_Verlust.TIMESTAMP))\n  AS value\nFROM Gewinne_Verlust\nJoin Gewinne_Verlust_PVonly on Gewinne_Verlust.time_sec=Gewinne_Verlust_PVonly.time_sec\nWHERE\n    $__unixEpochFilter(Gewinne_Verlust.time_sec)\nGROUP BY year(Gewinne_Verlust.TIMESTAMP)\n"
    }
   ]
  },
  {
   "title": "Einnahmen/Steuern/Gewinn(monatlich)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(Verkauf) as Verkauf,\n  sum(Ersparnis) as Ersparnis,\n  -sum(MWST) as MWST,\n  IF(sum(SteuerlGewinn)>sum(Abschreibung+MWST),sum(Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0) as SteuerGewinn,\n  (sum(Verkauf+Ersparnis-MWST-Abschreibung)+  IF(sum(SteuerlGewinn)>sum(Abschreibung+MWST),sum(Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0)) as Gewinn,\n  (sum(Verkauf-BezugKosten-MWST-Abschreibung)+  IF(sum(SteuerlGewinn)>sum(Abschreibung+MWST),sum(Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0)) as GesÜberschuss,\n  -sum(Abschreibung) as Abschreibung\nFROM Gewinne_Verlust\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY year(TIMESTAMP),month(TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n  Gewinne_Verlust.time_sec AS \"time\",\n  \"BatVorteil\" as metrics,\n  (IF (sum(Gewinne_Verlust.SteuerlGewinn)>sum(Gewinne_Verlust.Abschreibung+Gewinne_Verlust.MWST), (sum(Gewinne_Verlust.Abschreibung+Gewinne_Verlust.MWST)-sum(Gewinne_Verlust.SteuerlGewinn))*$Steuersatz,0)+sum(Gewinne_Verlust.Verkauf-Gewinne_Verlust.BezugKosten-Gewinne_Verlust.MWST-Gewinne_Verlust.Abschreibung) \n  -(IF (sum(Gewinne_Verlust_PVonly.SteuerlGewinn)>sum(Gewinne_Verlust_PVonly.Abschreibung+Gewinne_Verlust_PVonly.MWST), (sum(Gewinne_Verlust_PVonly.Abschreibung+Gewinne_Verlust_PVonly.MWST)-sum(Gewinne_Verlust_PVonly.SteuerlGewinn))*$Steuersatz,0)+sum(Gewinne_Verlust_PVonly.Verkauf-Gewinne_Verlust_PVonly.BezugKosten-Gewinne_Verlust_PVonly.MWST-Gewinne_Verlust_PVonly.Abschreibung) ))\n  AS value\nFROM Gewinne_Verlust\nJoin Gewinne_Verlust_PVonly on Gewinne_Verlust.time_sec=Gewinne_Verlust_PVonly.time_sec\nWHERE\n    $__unixEpochFilter(Gewinne_Verlust.time_sec)\nGROUP BY year(Gewinne_Verlust.TIMESTAMP),month(Gewinne_Verlust.TIMESTAMP)\n"
    }
   ]
  },
  {
   "title": "Gewinnentwicklung",
   "type": "graph",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  T1.time,\n  -15565.20*POW(1+$zinssatz,YEAR(T1.TIMESTAMP)-2019+1)+sum(T1.value) over (order by T1.grouping) as value,\n  \"Gewinn (Jahr)\" as metrics\n  FROM (\n    SELECT\n      max(time_sec) AS \"time\",\n      TIMESTAMP as TIMESTAMP,\n      (sum(Verkauf+Ersparnis-MWST) +  IF(sum(SteuerlGewinn)>sum(Abschreibung+MWST),sum(Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0)) as value,\n     YEAR(TIMESTAMP) as grouping\n    FROM Gewinne_Verlust\n    WHERE\n      $__unixEpochFilter(time_sec)\n    GROUP BY YEAR(TIMESTAMP)\n  )T1\n  group by T1.grouping"
    },
    {
     "rawSql": "SELECT\n  T1.time,\n  -15565.20*POW(1+$zinssatz,YEAR(T1.TIMESTAMP)-2019+1)+sum(T1.value) over (order by T1.grouping) as value,\n  \"Gewinn\" as metrics\n  FROM (\n    SELECT\n      max(time_sec) AS \"time\",\n      TIMESTAMP as TIMESTAMP,\n      (sum(Verkauf+Ersparnis-MWST) +  IF(sum(SteuerlGewinn)>sum(Abschreibung+MWST),sum(Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0)) as value,\n      Date_format(min(TIMESTAMP),\"%Y%m\") as grouping\n    FROM Gewinne_Verlust\n    WHERE\n      $__unixEpochFilter(time_sec)\n    GROUP BY YEAR(TIMESTAMP), MONTH(TIMESTAMP)\n  )T1\n  group by T1.grouping"
    },
    {
     "rawSql": "SELECT\n  T1.time,\n  -10675.20*POW(1+$zinssatz,YEAR(T1.TIMESTAMP)-2019+1)+4890*(POW(1+$zinssatz,YEAR(T1.TIMESTAMP)-2019+1)-1)+sum(T1.value) over (order by T1.grouping) as value,\n  \"Gewinn (ohneBat) (Jahr)\" as metrics\nFROM (\n  SELECT\n    max(time_sec) AS \"time\",\n      TIMESTAMP as TIMESTAMP,\n    (sum(Verkauf+Ersparnis-MWST) +  IF(sum(SteuerlGewinn)>sum(Abschreibung+MWST),sum(Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0)) as value,\n    YEAR(TIMESTAMP) as grouping\n  FROM Gewinne_Verlust_PVonly\n  WHERE\n    $__unixEpochFilter(time_sec)\n  GROUP BY YEAR(TIMESTAMP)\n)T1\ngroup by T1.grouping"
    },
    {
     "rawSql": "SELECT\n  T1.time,\n  -10675.20*POW(1+$zinssatz,YEAR(T1.TIMESTAMP)-2019+1)+4890*(POW(1+$zinssatz,YEAR(T1.TIMESTAMP)-2019+1)-1)+sum(T1.value) over (order by T1.grouping) as value,\n  \"Gewinn (ohneBat)\" as metrics\nFROM (\n  SELECT\n    max(time_sec) AS \"time\",\n      TIMESTAMP as TIMESTAMP,\n    (sum(Verkauf+Ersparnis-MWST) +  IF(sum(SteuerlGewinn)>sum(Abschreibung+MWST),sum(Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0)) as value,\n    Date_format(min(TIMESTAMP),\"%Y%m\") as grouping\n  FROM Gewinne_Verlust_PVonly\n  WHERE\n    $__unixEpochFilter(time_sec)\n  GROUP BY YEAR(TIMESTAMP), MONTH(TIMESTAMP)\n)T1\ngroup by T1.grouping"
    },
    {
     "rawSql": "SELECT\n  T1.time,\n  -15565.20*POW(1+$zinssatz,YEAR(T1.TIMESTAMP)-2019+1)+sum(T1.value) over (order by T1.grouping) as value,\n  \"GesÜberschuss (Jahr)\" as metrics\n  FROM (\n    SELECT\n      max(time_sec) AS \"time\",\n      TIMESTAMP as TIMESTAMP,\n      (sum(Verkauf-BezugKosten-MWST) +  IF(sum(SteuerlGewinn)>sum(Abschreibung+MWST),sum(Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0)) as value,\n      YEAR(TIMESTAMP) as grouping\n    FROM Gewinne_Verlust\n    WHERE\n      $__unixEpochFilter(time_sec)\n    GROUP BY YEAR(TIMESTAMP)\n  )T1\n  group by T1.grouping"
    },
    {
     "rawSql": "SELECT\n  T1.time,\n  -15565.20*POW(1+$zinssatz,YEAR(T1.TIMESTAMP)-2019+1)+sum(T1.value) over (order by T1.grouping) as value,\n  \"GesÜberschuss\" as metrics\n  FROM (\n    SELECT\n      max(time_sec) AS \"time\",\n      TIMESTAMP as TIMESTAMP,\n      (sum(Verkauf-BezugKosten-MWST) +  IF(sum(SteuerlGewinn)>sum(Abschreibung+MWST),sum(Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0)) as value,\n      Date_format(min(TIMESTAMP),\"%Y%m\") as grouping\n    FROM Gewinne_Verlust\n    WHERE\n      $__unixEpochFilter(time_sec)\n    GROUP BY YEAR(TIMESTAMP), MONTH(TIMESTAMP)\n  )T1\n  group by T1.grouping"
    }
   ]
  },
  {
   "title": "Einnahmen/Steuern/Gewinn(jährlich)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  sum(Verkauf) as Verkauf,\n  sum(Ersparnis) as Ersparnis,\n  -sum(MWST) as MWST,\n  IF(sum(SteuerlGewinn)>sum(Abschreibung+MWST),sum(Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0) as SteuerGewinn,\n  (sum(Verkauf+Ersparnis-MWST-Abschreibung)+  IF(sum(SteuerlGewinn)>sum(Abschreibung+MWST),sum(Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0)) as Gewinn,\n  (sum(Verkauf-BezugKosten-MWST-Abschreibung)+  IF(sum(SteuerlGewinn)>sum(Abschreibung+MWST),sum(Abschreibung+MWST-SteuerlGewinn)*$Steuersatz,0)) as GesÜberschuss,\n  -sum(Abschreibung) as Abschreibung\nFROM Gewinne_Verlust\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY year(TIMESTAMP)"
    },
    {
     "rawSql": "SELECT\n  Gewinne_Verlust.time_sec AS \"time\",\n  \"BatVorteil\" as metrics,\n  (IF (sum(Gewinne_Verlust.SteuerlGewinn)>sum(Gewinne_Verlust.Abschreibung+Gewinne_Verlust.MWST), (sum(Gewinne_Verlust.Abschreibung+Gewinne_Verlust.MWST)-sum(Gewinne_Verlust.SteuerlGewinn))*$Steuersatz,0)+sum(Gewinne_Verlust.Verkauf-Gewinne_Verlust.BezugKosten-Gewinne_Verlust.MWST-Gewinne_Verlust.Abschreibung) \n  -(IF (sum(Gewinne_Verlust_PVonly.SteuerlGewinn)>sum(Gewinne_Verlust_PVonly.Abschreibung+Gewinne_Verlust_PVonly.MWST), (sum(Gewinne_Verlust_PVonly.Abschreibung+Gewinne_Verlust_PVonly.MWST)-sum(Gewinne_Verlust_PVonly.SteuerlGewinn))*$Steuersatz,0)+sum(Gewinne_Verlust_PVonly.Verkauf-Gewinne_Verlust_PVonly.BezugKosten-Gewinne_Verlust_PVonly.MWST-Gewinne_Verlust_PVonly.Abschreibung) ))\n  AS value\nFROM Gewinne_Verlust\nJoin Gewinne_Verlust_PVonly on Gewinne_Verlust.time_sec=Gewinne_Verlust_PVonly.time_sec\nWHERE\n    $__unixEpochFilter(Gewinne_Verlust.time_sec)\nGROUP BY year(Gewinne_Verlust.TIMESTAMP)\n"
    }
   ]
  }
 ]
}