{
 "title": "11 Batvergleich",
 "tags": [ "PV" ],
 "time": { "from": "now-1d/d", "to": "now/d" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "days",
    "label": "Tage",
    "query": "0d,1d,2d,3d,4d,5d,6d,7d,8d,9d,10d"
   }
  ]
 },
 "panels": [
  {
   "title": "Zeit",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "string",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "SELECT\n  Date_format(TIMESTAMP,'%d.%m.%Y %k:%i') as value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Datum",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "SELECT\n  Date_format(TIMESTAMP,'%d.%m.%Y') as value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 9, "x": 7, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"WR: Sum (timerange)\" as \"type\",\n  sum(BatPowerLaden)/60000 AS \"Bat Laden\",\n  sum(BatPowerEntladen)/60000 AS \"Bat\"\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)"
    },
    {
     "rawSql": "SELECT\n  \"BYD: Sum (timerange)\" as \"type\",\n  max(Laden_kWh)-min(Laden_kWh) AS \"Bat Laden\",\n  max(EntLaden_kWh)-min(EntLaden_kWh) AS \"Bat\"\nFROM BYD_Daten\nWHERE\n  $__unixEpochFilter(time_sec)"
    }
   ]
  },
  {
   "title": "PV Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  dcPowerPV AS \"PV Power\",\n  BatPowerEntLaden AS \"Bat Power\",\n  acPower AS WR,\n  -BatPowerLaden AS \"Bat Laden\",\n  EinspeisenPower AS Einspeisen\n  /* (AktHomeConsumptionSolar+AktHomeConsumptionBat)/acPower AS Eigenverbrauchsanteil */\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nOrder By time_sec"
    }
   ]
  },
  {
   "title": "Spannungen / Ströme",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  round(time_sec,-1) AS time_sec,\n  PackVoltage_V as \"BYD: Bat Spannung\",\n  if(Current_A>0,Current_A,0) as \"BYD: Bat Strom Laden\",\n  if(Current_A<0,-Current_A,0) as \"BYD: Bat Strom Entnahme\"\nFROM BYD_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    },
    {
     "rawSql": "SELECT\n  round(time_sec,-1) AS time_sec,\n  BatVoltage as \"WR: Bat Spannung\",\n  if(BatCurrentDir = 0,BatCurrent,0) as \"WR: Bat Strom Laden\",\n  if(BatCurrentDir = 1,BatCurrent,0) as \"WR: Bat Strom Entnahme\"\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "Batterie - Entnahme",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  \"Entladen (WR)\" AS metric,\n  avg(BatPowerEntladen) AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY time_sec DIV 300"
    },
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  \"Entladen (BYD)\" AS metric,\n  (max(Entladen_kWh)-min(Entladen_kWh))*12000 as value\nFROM BYD_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY time_sec DIV 300"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"kWh Entladen\" AS metric,\n  sum(BatPowerEntladen)/60000 AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY to_days(timestamp),hour(timestamp)"
    },
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  \"kWh Entladen (BYD)\" AS metric,\n  (max(Entladen_kWh)-min(Entladen_kWh)) as value\nFROM BYD_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY to_days(timestamp),hour(timestamp)"
    }
   ]
  },
  {
   "title": "Batterie - Laden",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  \"Laden\" AS metric,\n  avg(BatPowerLaden) AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY time_sec DIV 300"
    },
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  \"Laden (BYD)\" AS metric,\n  (max(Laden_kWh)-min(Laden_kWh))*12000 as value\nFROM BYD_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY time_sec DIV 300"
    },
    {
     "rawSql": "SELECT\n  time_sec,\n  \"kWh Laden\" AS metric,\n  sum(BatPowerLaden)/60000 AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY to_days(timestamp),hour(timestamp)"
    },
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  \"kWh Laden (BYD)\" AS metric,\n  (max(Laden_kWh)-min(Laden_kWh)) as value\nFROM BYD_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY to_days(timestamp),hour(timestamp)"
    }
   ]
  },
  {
   "title": "Batterie -SOC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  round(time_sec,-1) as time_sec,\n  \"Ladestand (WR)\" AS metric,\n  avg(BatStateOfCharge) AS value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY time_sec DIV 300"
    },
    {
     "rawSql": "SELECT\n  round(time_sec,-1) as time_sec,\n  \"Ladestand (BYD)\" AS metric,\n  SOC\nFROM BYD_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "Cell Spanungen...",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "volt", "label": "Spannung" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  \"PackVoltage_V\" as \"metrics\",\n  PackVoltage_V/7/16\nFROM BYD_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    },
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  MaxCellVol_V,\n  MinCellVol_V,\n  MaxVolPos,\n  MinVolPos\nFROM BYD_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "Temperaturen...",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "celsius", "label": "Temperatur" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  SysTemp_C,\n  MaxCellTemp_C,\n  MinCellTemp_C,\n  MaxTempPos,\n  MinTempPos\nFROM BYD_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "NR Cycles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(time_sec,$__interval),\n  max(Laden_kWh)-min(Laden_kWh) AS Laden_kWh,\n  max(Entladen_kWh)-min(Entladen_kWh) AS Entladen_kWh,\n  CycleCounts AS Counts\nFROM BYD_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nGROUP BY CycleCounts"
    }
   ]
  },
  {
   "title": "Capacity estimation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  T1.time_sec as time_sec,\n  avg(T1.value) as value,\n  metrics\nFROM\n(SELECT\n  time_sec+3*3600 AS \"time_sec\",\n  avg(BatPowerEntLaden)*7*100/(max(BatStateOfCharge)-min(BatStateOfCharge)) as value,\n  \"Expected Capacity\" as metrics,\n  DATE_ADD(TIMESTAMP, INTERVAL 3 HOUR) as TIMESTAMP\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec+3*3600) and HOUR(DATE_ADD(TIMESTAMP, INTERVAL 3 HOUR))<8 and BatPowerLaden=0\nGroup by TO_DAYS(DATE_ADD(TIMESTAMP, INTERVAL 3 HOUR)))T1\nWhere T1.value>2\nGroup by year(T1.TIMESTAMP),month(T1.TIMESTAMP)"
    }
   ]
  }
 ]
}