{
 "title": "11 Bat Voltages",
 "tags": [ "PV" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "days",
    "label": "Tage",
    "query": "0d,1d,2d,3d,4d,5d,6d,7d,8d,9d,10d"
   },
   { "name": "module", "label": "Modul", "query": "1,2,3,4,5,6,7" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"WR: Sum (timerange)\" as \"type\",\n  sum(BatPowerLaden)/60000 AS \"Bat Laden\",\n  sum(BatPowerEntladen)/60000 AS \"Bat\"\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)"
    },
    {
     "rawSql": "SELECT\n  \"BYD: Sum (timerange)\" as \"type\",\n  max(Laden_kWh)-min(Laden_kWh) AS \"Bat Laden\",\n  max(EntLaden_kWh)-min(EntLaden_kWh) AS \"Bat\"\nFROM BYD_Daten\nWHERE\n  $__unixEpochFilter(time_sec)"
    }
   ]
  },
  {
   "title": "Spannungen / Ströme",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  round(time_sec,-1) AS time_sec,\n  PackVoltage_V as \"BYD: Bat Spannung\",\n  if(Current_A>0,Current_A,0) as \"BYD: Bat Strom Laden\",\n  if(Current_A<0,-Current_A,0) as \"BYD: Bat Strom Entnahme\"\nFROM BYD_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "Cell Spanungen...",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  \"PackVoltage_V\" as \"metrics\",\n  PackVoltage_V/7/16\nFROM BYD_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    },
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  MaxCellVol_V,\n  MinCellVol_V,\n  MaxVolPos,\n  MinVolPos\nFROM BYD_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec as time,\n  concat('modul: ',Module,' cell: ',Cell) as metric,\n  Voltage as ''\nFROM BYD_Voltage_Data\nWHERE\n  $__unixEpochFilter(time_sec) AND Array=1 \nOrder BY time_sec,Cell"
    },
    {
     "rawSql": "SELECT\n  round(time_sec,-1) as time_sec,\n  \"Ladestand (BYD)\" AS metric,\n  SOC\nFROM BYD_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    }
   ]
  },
  { "title": "Modul $module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }, "repeat": "module" },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec as time,\n  concat('cell ',Cell) as metric,\n  Voltage as ''\nFROM BYD_Voltage_Data\nWHERE\n  $__unixEpochFilter(time_sec) AND Array=1 AND Module=$module\nOrder BY time_sec,Cell"
    },
    {
     "rawSql": "SELECT\n  round(time_sec,-1) as time_sec,\n  \"Ladestand (BYD)\" AS metric,\n  SOC\nFROM BYD_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    }
   ]
  }
 ]
}