{
 "title": "22 Netzparameter",
 "tags": [ "PV" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "days",
    "label": "Tage",
    "query": "0d,1d,2d,3d,4d,5d,6d,7d,8d,9d,10d"
   },
   { "name": "DBname", "query": "${VAR_DBNAME}" },
   { "name": "Steuersatz", "query": "0.25,0.3,0.35,0.4" }
  ]
 },
 "panels": [
  {
   "title": "Datum",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "string",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "SELECT\n  Date_format(TIMESTAMP,'%d.%m.%Y') as value\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  AktHomeConsumptionSolar AS PV,\n  AktHomeConsumptionBat AS Batterie,\n  AktHomeConsumptionGrid AS Netz,\n  AktHomeConsumption AS Gesamt,\n  (AktHomeConsumptionSolar+AktHomeConsumptionBat)/AktHomeConsumption AS Autarkie\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nOrder BY time_sec"
    }
   ]
  },
  {
   "title": "Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  operatingStatus\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT  \nDate_format(TIMESTAMP,'%d.%m.%Y %k:%i') as \"Zeit\",\noperatingStatus as StatusCode,\n( Case operatingStatus\n  When 0 then 'off'\n  When 1 then 'anfahren'\n  When 2 then 'Leerlauf'  \n  When 3 then 'Einspeisen (MPP)'\n  When 4 then 'abgeregelt'\n  When 5 then 'Einspeisen'\n  Else 'undefined'\n  End) as Status\nFROM (\n    SELECT\n        operatingStatus,time_sec,TIMESTAMP,\n        @rn := CASE WHEN (@prev <> operatingStatus) THEN @rn+1 ELSE @rn END AS rn,\n    \t@prev := operatingStatus\n    FROM (\n        SELECT operatingStatus,time_sec,TIMESTAMP\n        FROM WR_Daten\n        WHERE $__unixEpochFilter(time_sec)\n        ORDER BY ID ) AS a , \n        (SELECT @prev := -1, @rn := 0) AS vars \n) T1 Group BY rn ORDER BY `T1`.`time_sec` DESC"
    }
   ]
  },
  {
   "title": "PV Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  dcPowerPV AS \"PV Power\",\n  BatPowerEntLaden AS \"Bat Power\",\n  acPower AS WR,\n  -BatPowerLaden AS \"Bat Laden\",\n  EinspeisenPower AS Einspeisen\n  /* sum(AktHomeConsumptionSolar+AktHomeConsumptionBat)/sum(acPower) AS Eigenverbrauchsanteil */\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nOrder BY time_sec"
    }
   ]
  },
  {
   "title": "Spannungen / Ströme (WR)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  dc1Voltage as \"String 1 Spannung\",\n  dc2Voltage as \"String 2 Spannung\",\n  dc1Current as \"String 1 Strom\",\n  dc2Current as \"String 2 Strom\",\n  BatVoltage as \"Bat Spannung\",\n  if(BatCurrentDir = 0,BatCurrent,0) as \"Bat Strom Laden\",\n  if(BatCurrentDir = 1,BatCurrent,0) as \"Bat Strom Entnahme\"\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "WR: Cos Phi",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  \"Cos Phi\" AS metric,\n  GridCosPhi\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "Netz: Spannungen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  GridVoltageL1 as \"L 1 Spannung\",\n  GridVoltageL2 as \"L 2 Spannung\",\n  GridVoltageL3 as \"L 3 Spannung\",\n  (GridVoltageL1+GridVoltageL2+GridVoltageL3)/3 as \"Spannung\"\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "Netz: Frequenz",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec AS \"time\",\n  \"Frequenz\" AS metric,\n  GridFreq\nFROM WR_Daten\nWHERE\n  $__unixEpochFilter(time_sec)\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "rawSql": "SELECT\n  GridCosPhi as \"CosPhi_dcPV\",\n  dcPowerPV as \"dcPV\",\n  \"dcPV\" as metrics_dcPV\nFROM WR_Daten\nWHERE\n  dcPowerPV>1 AND GridCosPhi >0 AND $__unixEpochFilter(time_sec)\nORDER BY dcPowerPV"
    },
    {
     "rawSql": "SELECT\n  GridCosPhi as \"CosPhi_acPV\",\n  acPower as \"acPV\",\n  \"acPV\" as metrics_acPV\nFROM WR_Daten\nWHERE\n  dcPowerPV>1 AND GridCosPhi >0 AND $__unixEpochFilter(time_sec)\nORDER BY acPower"
    },
    {
     "rawSql": "SELECT\n  GridCosPhi as \"CosPhi_einsp\",\n  EinspeisenPower as \"einsp\",\n  \"Einspeisen\" as metrics_einsp\nFROM WR_Daten\nWHERE\n  dcPowerPV>1 AND GridCosPhi >0 AND $__unixEpochFilter(time_sec)\nORDER BY EinspeisenPower"
    }
   ]
  }
 ]
}